### ISSUE TITLE
lightning kills player

### ISSUE THREAD

**Issue by Aikirob** [Sweenus/SimplySwords#1]
lightning constantly killing me

**Comment by Sweenus** [comment]
Thanks for the report.

Currently, a few of the unique weapons can cause bodily harm to the player. I'm looking into ways to mitigate this.

**Comment by Sweenus** [comment]
Storm status effect will now only spawn lightning if distance to player is more than 5 blocks. Storm radius increased by 5 blocks in all directions to compensate
