### ISSUE TITLE
Not every skill works along with the Wizards mod

### ISSUE THREAD

**Issue by MightyEmmo** [Sweenus/SimplySwords#103]
Hi! I'm using fabric, 1.20.1.
Not sure I am the only one having this issue, but some skills won't fully work as long the Wizards mod (and its dependecies) are there. With Hearthflame, there is the zoom and buffs, but the pulling of mobs just won't activate. Same thing with the gravity polearm (sorry, forgot its name), it just makes noises and moves a little up and down, but no skill. Normal hit passives works. With the 1.50 version, Emberblade would't work, but with the 1.48.1, it did. However, Hearthflame still did not.

**Comment by Sweenus** [comment]
Hi there,

This is on Spell Engines end. It breaks right click weapon functionality of other mods. To fix this, you need to blacklist all Simply Swords items in the server.json5 Spell Engine config.

`"blacklist_spell_casting_regex": "simplyswords:storms_edge|simplyswords:stormbringer|simplyswords:emberblade|simplyswords:hearthflame|simplyswords:soulkeeper|simplyswords:twisted_blade|simplyswords:soulstealer|simplyswords:soulrender|simplyswords:soul_pyre|simplyswords:frostfall|simplyswords:molten_edge|simplyswords:livyatan|simplyswords:icewhisper|simplyswords:arcanethyst|simplyswords:thunderbrand|simplyswords:mjolnir|simplyswords:waking_lichblade|simplyswords:awakened_lichblade|simplyswords:shadowsting",`

**Comment by Sylvitru** [comment]
Had the same issue, thanks for the help, @Sweenus! I blacklisted them and they no longer appear as castable weapon, yet I still have this issue. Is there anything else I can check or change? Tested in singleplayer with every mod updated (also fabric 1.20.1).

**Comment by Sweenus** [comment]
@MightyEmmo @Sylvitru Thank you for your reports! Re-opening the ticket.

I've identified an issue with the latest version of Simply Swords not respecting the Spell Engine blacklist in the server.json5. I deployed a method that was recommended to me by Daedelus, and was actually supposed to fix right click functionality out of the box without the need to add the items to the blacklist, but it appears to be achieving the opposite effect.

I've let Daedelus know. Hopefully this can be resolved on Spell Engine's side.

The affected weapons are: Mjolnir, Arcanethyst, Thunderbrand, Icewhisper, Lichblade, Stormbringer, Storm's Edge, and Hearthflame.

**Comment by Sweenus** [comment]
Just an update on this - Daedelus has squashed the bug.
However, he will not be able to push a Spell Engine update for another 10 or so days.

**Comment by MightyEmmo** [comment]
@Sweenus Thank you (and Daedelus) for you hard work.
Looking forward to playing with both of your mods.

**Comment by Sweenus** [comment]
Sorry for the delay in response!
This issue should now be resolved out of the box with the latest version of Simply Swords. No blacklisting required.
