### ISSUE TITLE
[BUG/GLITCH][Forge] 2Hand in Offhand, Item's in offhand gone after use F key on 2hand

### ISSUE THREAD

**Issue by Kiragatu** [Sweenus/SimplySwords#104]
Hey simple problem, I got a message from some guys on the Server, that their weapons do not exist any more.

I test it by myself:

If you hold in the "OFFHAND" a shield for example and  take a 2hand Sword or Scythe and use "F" (take item into OFFHAND'' ) “the shield is gone “ x), if you open now the inventory for check. You see the 2Hand weapon in the offhand, close the inventory and reopen it and the 2hand is also gone.

Maybe Fix it with the Blocking F key for 2hand if the toolbar is active on them? or do a blacklist for offhand and f key ?

I found nothing in time to Fix it by myself.

I hope you can find that BUG GLITCH also.

Have a nice day guys and sorry about my "bad English".

**Comment by Sweenus** [comment]
Hi there 👋 

That sounds like it's probably a bug with Better Combat if anything - Simply Swords doesn't do any of the 2H/1H weapon logic.
Please check in an instance with only Simply Swords and its dependencies installed if the issue still occurs.

**Comment by Kiragatu** [comment]
Year found it Thanks for that, its a problem of the Forge version 1.20.1 - 47.1.43 so better use the RE version 1.20.1 - 47.1.0 and older version of mods i guess.. , but we wait for the next RE version and hopefully a fix of that :)
