### ISSUE TITLE
Way Too Common

### ISSUE THREAD

**Issue by netrunnernumber37** [Sweenus/SimplySwords#105]
I feel like the swords are way too common considering how powerful they are compared to diamond and iron swords, was looting a village earlier and found one in the first 5 minutes of starting my world and it feels like the swords should be significantly more rare.

**Comment by Sweenus** [comment]
What version are you using? They shouldn't even be appearing in villages by default.

**Comment by netrunnernumber37** [comment]
I have quite a few village mods as well to be fair, and is more likely an issue with that mod not using village loot tables, but I am using 1.50.1.

**Comment by Sweenus** [comment]
That is likely the issue.
I'd recommend tweaking the config values to get a loot rate that best matches your modpack.
