### ISSUE TITLE
What version of SimplySwords is compatible with Backslot 1.2.8?

### ISSUE THREAD

**Issue by Foxificer** [Sweenus/SimplySwords#106]
**Minecraft Version**
What version of Minecraft are you using? 1.19

**Mod Version**
What version of Simply Swords are you using? simplyswords-fabric-1.43.1-1.19.2

**Describe the bug**
Backslot weapons are to big, would like to know which version of SimplySwords is compatible with Backslot 1.2.8 and also has the new textures?

**Comment by Sweenus** [comment]
You would need to update your Backslot mod version to 1.2.10. They changed the way they read model data in that version. I added proper support for the updated version.
