### ISSUE TITLE
How to turn off the default guidebook when you first enter the world?

### ISSUE THREAD

**Issue by Kogomre** [Sweenus/SimplySwords#107]
**Minecraft Version**
1.20.1

**Mod Version**
Simplyswords-forge-1.51.0-1.20.1.jar

**Comment by Sweenus** [comment]
Hi there,

You can disable this by creating a datapack targeting the following file: https://github.com/Sweenus/SimplySwords/blob/Architectury-1.20/common/src/main/resources/data/simplyswords/advancements/grant_book_on_first_join.json
