### ISSUE TITLE
runic_halberd missing from advancements/runic_weapon

### ISSUE THREAD

**Issue by ActuallyBlue** [Sweenus/SimplySwords#108]
Latest Fabric version ( 0.11.2  1.20.1 )

Latest mod version ( v1.50.0  1.20.1 )

The bug is fairly simple and also not important but holding any runic weapon will give you the "Rune Etching" advancement in game (runic_weapon file name), but a runic halberd specifically will not.

Pretty sure this is the only case where a weapon isn't checked for, though haven't looked through compat or mythic metal files, or every weapon specifically.

-

Somethings that are possibly not a bug and intended; The runes on a runic halberd are blurrier than other weapons, and all halberds having a significantly different handle color

**Comment by Sweenus** [comment]
Thank you for the report!
This has been fixed in the latest version (1.51.5)
