### ISSUE TITLE
Feedback from a modpack dev

### ISSUE THREAD

**Issue by itsdinkd** [Sweenus/SimplySwords#11]
Hi, i'm the creator of AQM2. Though your mod is wonderful, it lacks a lot of information surrounding the effects and config values which are highly important to us modpack developers. 

I'm not sure what half of these statuses do as well as the configs. What is watcher for example? what does the restore amount do? what about soulmeld, or soulrend? especially omen, no idea how the instakill mechanic works. as well as ferocity. It would be wonderful if you can create a wiki to explain the effects / config values or at least add comments in the config. 

Also is the duration in seconds or ticks?

Thanks!

**Comment by Sweenus** [comment]
Hey there,

Thanks for including the mod in your modpack, and great suggestion!
I'm coincidentally in the process of completely overhauling the configuration to provide more information, and allow more granular adjustments (Eg. complete control over attack damage / attack speed for each weapon) - I think this is particularly important when included in a pack with other mods as the unique weapon damage modifiers can be somewhat underwhelming when paired against the power creep from some other notable mods.

It should be packaged with the next release (In the next few days hopefully).
If you have any questions on the config values in the interim, please feel free to @ or DM me on Discord - Always happy to help :)

PS. Duration is in ticks.

**Comment by Sweenus** [comment]
To give you an idea, here's a look at the new weapons attributes config.
The rest of the configs will follow a similar format (and won't be a jumbled mess anymore).
[weapon_attributes.txt](https://github.com/Sweenus/SimplySwords/files/9630743/weapon_attributes.txt)

**Comment by Sweenus** [comment]
Configs have been greatly expanded upon in the latest release - they should now be fit for modpack creation.
If you have any further feedback regarding them, please feel free to @ me on Discord or submit another ticket.

In regards to AQM2, I'd recommend upping the damage modifiers for the unique weapons to be in line with the power creep of other mods, such as Mythic Metals.

**Comment by itsdinkd** [comment]
Thanks!!

As for damage modifying; good call

**Comment by itsdinkd** [comment]
finally had the chance to check out the configs, it looks like there are some descriptions missing still. some I was able to see on the mod page, but the others I wasn't.

// -- Unique Effect: Soul Meld -- 
// ----------------------------- 
  "soulmeld_chance": 75.0,
  "soulmeld_duration": 250.0,
  "soulmeld_radius": 5.0,

// -- Unique Effect: Soul Rend -- 
// ----------------------------- 
  "soulrend_chance": 85.0,
  "soulrend_duration": 500.0,
  "soulrend_rend_damage_multiplier": 2.0,
  "soulrend_rend_heal_multiplier": 0.5,
  "soulrend_radius": 10.0,
  "soulrend_max_stacks": 8.0,

// -- Unique Effect: Ferocity -- 
// ----------------------------- 
  "ferocity_chance": 75.0,
  "ferocity_duration": 100.0,
  "ferocity_max_stacks": 15.0,
  "ferocity_strength_tier": 2.0,

// -- Unique Effect: Ember Ire -- 
// ------------------------------ 
  "ember_ire_chance": 5.0,
  "ember_ire_duration": 150.0,

// -- Unique Effect: Volcanic Fury -- 
// ---------------------------------- 
  "volcanic_fury_chance": 25.0,

// -- Unique Effect: Storm -- 
// -------------------------- 
  "storm_chance": 15.0,
  "storm_radius": 10.0,

// -- Unique Effect: Plague -- 
// --------------------------- 
  "plague_chance": 55.0,

// -- Unique Effect: Brimstone -- 
// ------------------------------ 
  "brimstone_chance": 15.0,
  "bramble_chance": 45.0,
  "bramble_radius": 10.0

**Comment by Sweenus** [comment]
These descriptions are available in-game in the item tooltips. Each Unique effect is named and described on its weapon.

Were you aware of this? Or do you think the information should be added to the config itself?
My thinking is that someone will go into the config knowing the name of the ability they are trying to change, and that adding every weapon description in there would add unnecessary bloat and ruin readability.

Interested to hear your thoughts before I make any changes

**Comment by E3VL** [comment]
> These descriptions are available in-game in the item tooltips. Each Unique effect is named and described on its weapon.
> 
> Were you aware of this? Or do you think the information should be added to the config itself? My thinking is that someone will go into the config knowing the name of the ability they are trying to change, and that adding every weapon description in there would add unnecessary bloat and ruin readability.
> 
> Interested to hear your thoughts before I make any changes

Hello, I was wondering if there is a way to set the tooltips or anything like that.
Reason im asking is Im testing a modpack for my clan V3X, and one of the weapons is causing a crash because the tooltip doesnt exist.
