### ISSUE TITLE
How does Arcanethyst work?

### ISSUE THREAD

**Issue by mauryceG** [Sweenus/SimplySwords#111]
I've got Arcanethhyst from a chest, a great looking weapon, but how does its skill work ? i press the right button but it only makes a sound

**Comment by EnderGirl1500** [comment]
I tried it and got no effect as well, plus the FPS drop I mentioned in #114

**Comment by Sweenus** [comment]
You need to hold right mouse button, not press.

If it's still not working while holding then you probably have Spell Engine installed. See: https://github.com/Sweenus/SimplySwords/issues/103
