### ISSUE TITLE
Applying Netherinfused Gem or general Gem Simply Swords

### ISSUE THREAD

**Issue by toqql123** [Sweenus/SimplySwords#115]
**Minecraft Version**
1.20.1 / Playing the Modpack Prominence II Fabric 1.20.1

**Mod Version**
v1.51.0 Fabric

**Describe the bug**
There is no current way to infuse any weapon from this Mod with a Netherinfused Gem or the other one. Normally it would work by using the Smithing Table but it doesnt work anymore and i tried everything else.

**Comment by Sweenus** [comment]
Netherfused gems have never been applied via smithing table. You simply click on the gem and then click on a weapon with the appropriate socket available. You can find all this documentation via the Runic Grimoire when Patchouli is installed.

**Comment by zekeflynn** [comment]
Not working for me for some reason, clicking different types of gems and trying to socket into different unique weapons does nothing just swaps the cursor item.

**Comment by Sweenus** [comment]
@zekeflynn
You need to ensure the weapon has the appropriate sockets available for the gems you're trying to insert.
