### ISSUE TITLE
Compatibility between Simply Swords (Fabric) /  Paladins & Priests (RPG Series) / Wizards (RPG Series).

### ISSUE THREAD

**Issue by TomBignell** [Sweenus/SimplySwords#116]
MC Version: 1.20.1
SS Mod Version: 1.20.1
P&P Mod Version: 1.20.1
Wizards Mod Version: 1.20.1
Mod Loader: Fabric 1.20.1

You cannot use the unique weapons abilities that require you to right click when you also have a spell book equipped from the Paladins & Priests mod, also the Wizards mod. The right clicking to activate spells overrides the function for the unique sword abilities. You have to remove the spell book from the trinket slot so you can use the unique weapon ability again, which when you're in combat, you don't really have time to do. This also means, that while in a combat, it renders major parts of either mod essentially redundant if one cannot be used with the other when you need it most.

I am mentioning this as in your other mod "Simply Skills (Fabric)", you mention it the description to use the Crusader class in Paladins & Priests as an advised option.

While this issue has no relation specifically between the Simply Skills mod and the Paladins & Priests mod, since both 'Simply' mods are made by yourself, I assume you would want a seamless integration between all three/ four mods, hence why I am mentioning it :).

A simple way to fix this would just be to allow the user to change key/ mouse button bindings for the use of the unique weapon abilities. Perhaps getting in touch with a Dev for the Paladins & Priests mod and the Wizards mod to ask them to do the same would be good too if you all want compatibility. 

I have seen issue #103 but I do not think it's a spell engine issue. Just that all mods involved require the use of the same button.

**Your Simply Skills mod is incredible btw, best mod I've seen of it's type! However, the specialisations abilities are quite a bit overpowered I may add though. Especially with being able to use more than one specialised ability with the same key all at once**

**Comment by ELCuleroPingon** [comment]
"Your Simply Skills mod is incredible btw, best mod I've seen of it's type! However, the specialisations abilities are quite a bit overpowered I may add though" I wish we could modify the damage values for these abilities. I for one tested the ranger ones and they were underwhelming.

**Comment by Sweenus** [comment]
> "Your Simply Skills mod is incredible btw, best mod I've seen of it's type! However, the specialisations abilities are quite a bit overpowered I may add though" I wish we could modify the damage values for these abilities. I for one tested the ranger ones and they were underwhelming.

Hey there, best to use the Simply Skills github for suggestions relating to it, but I'm glad you like the mod!
Have a sus of the config in-game, you can tweak a LOT of the balance to suit your modpack.

**Comment by Sweenus** [comment]
All unique weapons in Simply Swords no longer cast Spell Engine spells by default. Make sure you update to the latest version.

Unfortunately, adding a keybind system for Simply Swords would take extensive rewrites that I don't currently have the time for. I may revisit in future if there is enough demand.
