### ISSUE TITLE
Compatibility with Mythic Upgrades

### ISSUE THREAD

**Issue by FumpleWumper** [Sweenus/SimplySwords#117]
Not to be confused with Mythic Metals which the mod is already compatible with, but could it work with Mythic Upgrades in the future? The mod adds a bunch of different upgrades like Netherite that all have their own use and I'd love to use this with the weapons in Simply Swords!
Thanks for reading and keep up the good work :]

**Comment by Sweenus** [comment]
Thank you for the kind words!
It looks like someone has made a compat mod for this here: https://www.curseforge.com/minecraft/mc-mods/simply-more-swords
(Please note, I have not tested this mod)
