### ISSUE TITLE
Lichblade AOE doesnt count as player damage

### ISSUE THREAD

**Issue by milkev** [Sweenus/SimplySwords#118]
**Minecraft Version**
1.20.1

**Mod Version**
1.48.1 fabric

**Describe the bug**
The aoe damage caused by the lichblade doesnt count as player damage. This means that anything hit by it or killed only by it; Will not aggro onto the player (ez endermen kill), will not drop exp and (as far as i can tell from very minimal testing) not be effected by looting

**To Reproduce**
Hold a lichblade.

**Comment by Sweenus** [comment]
Thank you for your report!
This should be fixed in the latest version (1.51.5).
