### ISSUE TITLE
Metallurgium Weapons

### ISSUE THREAD

**Issue by SpacePuffer** [Sweenus/SimplySwords#119]
**Minecraft Version**
1.20.1

**Mod Version**
1.51.1

**Describe the bug**
While Metallurgium weapons are on screen they cause drastic frame drop.

**Screenshots**
![image](https://github.com/Sweenus/SimplySwords/assets/144860705/a5158438-4e09-4801-8e9d-63e6629e116c)
![image](https://github.com/Sweenus/SimplySwords/assets/144860705/97f8ee1f-b418-485c-8de6-c6717dc966a2)

**Comment by Sweenus** [comment]
This is caused by Model Gap Fix mod. I'd suggest uninstalling it.
