### ISSUE TITLE
Watcher Warglaive virtually 1-shotting mobs

### ISSUE THREAD

**Issue by zekeflynn** [Sweenus/SimplySwords#120]
**Minecraft Version**
1.20.1

**Mod Version**
simplyswords-forge-1.51.0-1.20.1

**Describe the bug**
When dual wielding Watcher Warglaives, it seems occasionally something about the procs virtually 1 shot any mob the player is hitting. We aren't sure if the procs are based on % hp and so even bosses with 1000, 5000 or 10000 hp get chunked and seemingly one shot when it happens.

**To Reproduce**
Just fighting stuff with dual wield watcher warglaives.

**Screenshots**

**Crash/Latest log**
If applicable, add your log files here.

**Comment by Sweenus** [comment]
This is not a bug. The weapon has a chance to execute an enemy below 25% HP, as per the weapon tooltip.
You can configure this value in the config if it's not to your liking.
