### ISSUE TITLE
Compatability between Simply swords (Fabric) and Better combat (Fabric)

### ISSUE THREAD

**Issue by FoxmilianZerochan** [Sweenus/SimplySwords#121]
**Minecraft Version**
1.20.1

**Mod Version**
Fabric 1.51.1 - 1.20.1

**Describe the bug**
Cant use some abilities of legendary weapons while using better combat mod. For example awakened lichblade.

**To Reproduce**
1) Install better combat mod
2) Install simple swords
3) Get Awakened lichblade
4) Use Right click ability

**Comment by Sweenus** [comment]
This is a conflict with Spell Engine, not Better Combat. This is fixed as of the latest version of Simply Swords.
