### ISSUE TITLE
[Bug]Omen effect instakills above threshold

### ISSUE THREAD

**Issue by grundyboy34** [Sweenus/SimplySwords#124]
**Minecraft Version**
1.20.1

**Mod Version**
1.51.0-1.20.1 forge (47.1.3)

**Describe the bug**
Omen effect (using the watcher sword) sometimes instakills enemies and bosses when they're way above the set threshold (0.25)

**To Reproduce**
As the effect procs randomly, just try it until it happens.
I've noticed it instakill a warden at 480/500 health, and the empress of light from Stellarity at 97% health

**Additional Info**
Looks like some logic issues here: https://github.com/Sweenus/SimplySwords/blob/1de3ba5839ee527f6652250a08e198507898003e/common/src/main/java/net/sweenus/simplyswords/item/custom/WatcherSwordItem.java#L66C85-L66C85

**Comment by Sweenus** [comment]
Thank you for the report!
This should be fixed in the latest version (1.51.5).
