### ISSUE TITLE
How to implement Loot drops into nether and other sources etc.

### ISSUE THREAD

**Issue by ELCuleroPingon** [Sweenus/SimplySwords#125]
I am currently using the latest version of the mod, but cant help but notice that the chests within bastions and nether fortresses don't contain any of the Simply Swords weapons, I have found runes, but no weapons. I actually found this odd after like 20-25 chests and opened up private creating world and tp'd around to not find any is there a way to add them into those loot tables in the config files?

**Comment by Sweenus** [comment]
Hello,

If you're finding runes, that implies that the loot injection is working correctly, and that you can find the weapons in the same location. Simply Swords injects loot into all chest loot tables (except villages) by default.
If a pack has loot table changes via datapack this can override my injection method and result in loot not showing (you wouldn't be seeing the runic tablets in this case though).

You shouldn't need to, but you can try manually adding the loot table path to the config file found in the simplyswords_extra folder.

**Comment by ELCuleroPingon** [comment]
Pardon my ignorance all this is relatively new to me but what would be the file path to the chests in the Nether Fortresses and Bastions?


I notice the other ones state 'minecraft:chests/village/ etc. so would it be
Minecraft:chests/Nether_fortress

**Comment by Sweenus** [comment]
Sorry for the delayed response!
I'm not actually sure what the Nether fortress loot path is, it does not appear to be located under /chests like I would have thought.

Here are the vanilla paths that Simply Swords will generate in by default:

- minecraft:chests/ancient_city_ice_box
- minecraft:chests/simple_dungeon
- minecraft:chests/village/village_mason
- minecraft:chests/village/village_temple
- minecraft:chests/bastion_treasure
- minecraft:chests/ruined_portal
- minecraft:chests/village/village_fisher
- minecraft:chests/village/village_toolsmith
- minecraft:chests/shipwreck_map
- minecraft:chests/shipwreck_supply
- minecraft:chests/village/village_snowy_house
- minecraft:chests/stronghold_crossing
- minecraft:chests/nether_bridge
- minecraft:chests/abandoned_mineshaft
- minecraft:chests/shipwreck_treasure
- minecraft:chests/stronghold_corridor
- minecraft:chests/village/village_fletcher
- minecraft:chests/village/village_tannery
- minecraft:chests/spawn_bonus_chest
- minecraft:chests/village/village_plains_house
- minecraft:chests/underwater_ruin_small
- minecraft:chests/buried_treasure
- minecraft:chests/village/village_armorer
- minecraft:chests/bastion_hoglin_stable
- minecraft:chests/desert_pyramid
- minecraft:chests/underwater_ruin_big
- minecraft:chests/igloo_chest
- minecraft:chests/ancient_city
- minecraft:chests/bastion_bridge
- minecraft:chests/pillager_outpost
- minecraft:chests/village/village_shepherd
- minecraft:chests/village/village_cartographer
- minecraft:chests/jungle_temple_dispenser
- minecraft:chests/jungle_temple
- minecraft:chests/village/village_savanna_house
- minecraft:chests/village/village_taiga_house
- minecraft:chests/village/village_butcher
- minecraft:chests/village/village_desert_house
- minecraft:chests/end_city_treasure
- minecraft:chests/stronghold_library
- minecraft:chests/village/village_weaponsmith
- minecraft:chests/bastion_other
- minecraft:chests/woodland_mansion
