### ISSUE TITLE
Crash when using mod with arclight

### ISSUE THREAD

**Issue by HEofOttoman** [Sweenus/SimplySwords#126]
**Minecraft Version**
1.20.1

**Mod Version**
FORGE v1.51.4-1.20.1

**Describe the bug**
Arclight gives the following message in the log before crashing.
[14Oct2023 15:04:11.948] [main/WARN] [mixin/]: Reference map 'simplyswords-common-refmap.json' for simplyswords-common.mixins.json could not be read. If this is a development environment you can ignore this message
--
28 | [14Oct2023 15:04:11.951] [main/WARN] [mixin/]: Reference map 'simplyswords-forge-refmap.json' for simplyswords.mixins.json could not be read. If this is a development environment you can ignore this message

**To Reproduce**
1. Make a server with Arclight on 1.20.1 on aternos.
2. Install Simply swords and dependencies along with Cristellib and Towns and towers (to pinpoint which mod has the issue).
3. Run the server and see if it crashes
**Screenshots**
None

**Crash/Latest log**
mclo.gs/S40jP66
Relevant Text: 
[14Oct2023 15:04:11.948] [main/WARN] [mixin/]: Reference map 'simplyswords-common-refmap.json' for simplyswords-common.mixins.json could not be read. If this is a development environment you can ignore this message
--
28 | [14Oct2023 15:04:11.951] [main/WARN] [mixin/]: Reference map 'simplyswords-forge-refmap.json' for simplyswords.mixins.json could not be read. If this is a development environment you can ignore this message

**Comment by Sweenus** [comment]
This is a warning, not a crash. This warning will not cause any issues.

Please upload your full crashlog

Edit: Just noticed the crashlog link. I'll take a look

**Comment by Sweenus** [comment]
This doesn't look like a full log, and I don't actually see any crash in it. Can you please upload the full crashlog?

**Comment by HEofOttoman** [comment]
Aternos doesn't write a crash for some reason
It just abruptly crashes.
I'll attempt to recreate the crash.

**Comment by HEofOttoman** [comment]
I have tried using the mod on a test server and it works.
It seems to might not be simply swords' fault.
I will open an issue on arclight instead
I'll close the issue for now.
