### ISSUE TITLE
[Bug?] Brimstone explosion destroys mob drops

### ISSUE THREAD

**Issue by harpuppy** [Sweenus/SimplySwords#130]
Brimstone Claymore appears to destroys drops if the mob is specifically killed by the explosion effect. If they die from melee or fall damage after getting blasted into the air, the drops are fine. Gamerules don't affect this

This doesn't seem intentional but if it is I suppose this is a suggestion to make it configurable.

**Comment by Sweenus** [comment]
This has been fixed in version 1.55.0 due for release later today.
