### ISSUE TITLE
config add_weapons_to_loot_tables 

### ISSUE THREAD

**Issue by Heraice** [Sweenus/SimplySwords#132]
In the config file "simplyswords_extra" "loot_config" you precise that we can enable an option called "add_weapons_to_loot_tables" which is supposed to be placed in the file "config file "simplyswords_main" but I cannot find it. 
Is it still injected in every loot table possible ? If not is there any simple solution for me to permit it ?
Thanks for your time and my apology if my question is silly I'm new to modding and modifying config

**Comment by Sweenus** [comment]
Terribly sorry for the delayed response.
If you are on the latest version of Simply Swords, it is just refering to the loot settings found in the General config. These are enabled by default, so there isn't anything extra you need to do.
