### ISSUE TITLE
Weapon Effects Affect Tamed/Summoned Friendly Mobs

### ISSUE THREAD

**Issue by fzzyhmstrs** [Sweenus/SimplySwords#133]
My poor hamsters got nuked last night by Kami using the active on her axe. It would be nice if those effects avoided `Tameable` mobs, or maybe Tameable mobs whose `getOwner` is a teammate, much like how the abilities dodge direct teammates now.

**Comment by Sandriell** [comment]
Similarly, Active Defense just shoots arrows at everything. It specifically says it targets enemies, so it should only attack hostiles.

**Comment by vincentscode** [comment]
I *think* this mod should already check to not attack tamed entities.
https://github.com/Sweenus/SimplySwords/blob/7fe6bc5f51621ba6599a4dac8fbcf4516237e99b/common/src/main/java/net/sweenus/simplyswords/util/HelperMethods.java#L110-L112
The Lichblade was still hurting nearby tamed entities though, even after manually adding the entity to the team.

**Comment by Sweenus** [comment]
This should be fixed in the latest version. Please let me know if it still occurs.
May the hamsters be at peace
