### ISSUE TITLE
Incompatibility with "Enchanted Origins"

### ISSUE THREAD

**Issue by MLMII** [Sweenus/SimplySwords#134]
Enchanted Origins adds an origin called Looting, which automatically adds levels of the looting enchantment to swords and axes, but the weapons added by Simply Swords aren't recognized.   I'm not sure if this is something that has to be fixed on the other mod but I figured I'd point it out just in case.

Thank you for your time.

Enchanted Origins   https://modrinth.com/mod/enchanted-origins

**Comment by Sweenus** [comment]
Hi there,

This is something that would need to be fixed on Enchanted Origins' end. The weapons in Simply Swords are all extensions of the vanilla SwordItem. They should just be able to target the SwordItem and have full compatibility with just about all weapons mods.
