### ISSUE TITLE
Feature Request - Config to not add runic manual to inventory automatically 

### ISSUE THREAD

**Issue by MLMII** [Sweenus/SimplySwords#135]
I was wondering if it would be possible to add a config option to not automatically add the book to my inventory?

Thank you for your time.

**Comment by ghost** [comment]
I also want to know how to configure it so that the book does not appear when the world is first created!
(i mean the guide book)

**Comment by Broseten** [comment]
It seems patchouli is responsible for that. [Here](https://github.com/Sweenus/SimplySwords/blob/7fe6bc5f51621ba6599a4dac8fbcf4516237e99b/common/src/main/resources/data/simplyswords/advancements/grant_book_on_first_join.json#L22) is the file doing that.
However I haven't figured out a any way to disable it. Might be doable through datapacks?

Anyway, upvote for this.

**Comment by MarioSMB** [comment]
Pardon the rant but it's a pet peeve of mine that mods still insist on making their content front and center with these books cluttering your inventory on spawn... and disabling it is getting harder each update!  

Regarding disabling it, you should be able to do so with a datapack using an advancement file of the same name with something like this in it: https://www.minecraftforum.net/forums/minecraft-java-edition/redstone-discussion-and/commands-command-blocks-and/2952119-disable-advancements-without-error-spam?comment=2

**Comment by Sweenus** [comment]
This must be done via datapack.

**Comment by MarioSMB** [comment]
Here’s hoping mod developers find a better way to showcase what their mod has to offer someday…

**Comment by Sweenus** [comment]
> Here’s hoping mod developers find a better way to showcase what their mod has to offer someday…

Do you have suggestions?
I have kept your ticket here open for consideration in the future: https://github.com/Sweenus/SimplySwords/issues/154

I have implemented both patchouli support and a dedicated wiki as requested by many users. Updating both of these when new items & features are added adds significant time and effort to my update process. If a better alternative exists, I would gladly adopt it - but to my knowledge, no better in-game documentation system has been created in this space.

**Comment by MarioSMB** [comment]
It is understandably a difficult subject to tackle, as some documentation is better than no documentation - especially when more complicated mechanics are involved.  
With that in mind, I appreciate your open mindness and will propose some alternatives and suggestions in that issue report, thanks.
