### ISSUE TITLE
Animated Unique swords decreases FPS by ALOT

### ISSUE THREAD

**Issue by Kaizuto** [Sweenus/SimplySwords#136]
What the title says, holding the unique weapons decreases fps by a lot even when just in hotbar or dropped.

Holding brimstone claymore:
![image](https://github.com/Sweenus/SimplySwords/assets/83712471/156ba959-5193-4d98-98cf-1f77e752828b)

Not holding brimstone claymore:
![image](https://github.com/Sweenus/SimplySwords/assets/83712471/8b973955-c29d-45b7-a5d3-1e639d48593a)

**Comment by Kaizuto** [comment]
another example, holding lichblade:
![image](https://github.com/Sweenus/SimplySwords/assets/83712471/fdda5d6e-0628-48f8-adc4-4b182f3c014f)

**Comment by Sweenus** [comment]
Uninstall Model Gap Fix: https://github.com/MehVahdJukaar/modelfix-multi/issues/27
