### ISSUE TITLE
1.47 1.19.2 Frost Hammer Unique Right Click Crashes Game

### ISSUE THREAD

**Issue by SangurianSoul** [Sweenus/SimplySwords#141]
I just downloaded the Mod since the last time I used it, (probably 8 moths ago at this point.) Saw a Frost hammer unique i did not recognize. I went to use its Right Click power, to see how it worked, and it crashed may game.

Not only that, but the game crashes instantly upon rejoining the world as well. Even removing the mod from the list and trying to rejoin will not fix it. I'm basically locked out of my world and I cant play.

[crash-2024-01-05_11.06.29-client.txt](https://github.com/Sweenus/SimplySwords/files/13844854/crash-2024-01-05_11.06.29-client.txt)

**Comment by Sweenus** [comment]
This appears to be a Twilight Forest crash. You will need to contact their devs for support, or try removing the mod.
