### ISSUE TITLE
[Suggestion] Adding Runic Upgrade for Vanilla Netherite Tools and Armor

### ISSUE THREAD

**Issue by CaptConrad** [Sweenus/SimplySwords#142]
I don't know what plans y'all have for future updates to the mod but may I suggest adding runic upgrades of vanilla netherite tools and possibly even netherite armor. Would love to have that consistency instead of the runic tablet being only for simply sword weapons.

**Comment by Sweenus** [comment]
Hi there,

Sorry for the delayed response, and thank you for the suggestion.
This would be out of scope for Simply Swords, but I'm not against the idea of runic armor & tools being added in their own respective mods.

I will keep this in consideration 🙂
