### ISSUE TITLE
[Compatibility] Mythic Upgrades

### ISSUE THREAD

**Issue by Lunaticol** [Sweenus/SimplySwords#148]
Mythic Upgrades introduces an array of five new ore types, each accompanied by its unique weaponry. Here's a rundown of the weapons:

    Jade: This weapon carries a deadly venom, inflicting poison upon foes with each strike.
    
    Topaz: weapons crafted from Topaz have triple the endurance of standard equipment.
    
    Aquamarine: Aquamarine weaponry has the ability to freeze adversaries upon impact, rendering them immobile and vulnerable.
    
    Sapphire: weapons deal additional damage equivalent to 5% of the enemy's maximum health
    
    Ruby: Ruby weapons allow for swifter attacks, providing a decisive edge in combat.
    
    Ametrine: Ametrine weaponry possesses the ability to levitate enemies upon contact

With over 3 million downloads on CurseForge, Mythic Upgrades has cemented its status as a must-have addition to any Minecraft player's arsenal. However, despite its widespread popularity, its compatibility with other mods remains somewhat limited, leaving room for further development and integration. Incorporating compatibility with Simply Swords, would elevate the gameplay experience for users of both modifications.

**Comment by Sweenus** [comment]
Hi there,
It looks like someone has made a compat mod for this: https://www.curseforge.com/minecraft/mc-mods/simply-more-swords
(please note - I have not tested this mod)
