### ISSUE TITLE
More unique base stats

### ISSUE THREAD

**Issue by Kuggle01** [Sweenus/SimplySwords#15]
IDK if it's any different with better combat installed, but without it weapons that should have extra stats like extra reach or better sweeping do not, and I think it'd be a huge improvment if you could implement that. Alterntively it might just be that these extra stats don't display on the weapon and I just haven't notied them, if this is the case I think adding a bit too the tooltip that displays extra range or sweeping for weapons where it is applicable would be a huge improvement

**Comment by Sweenus** [comment]
Thanks for leaving your feedback!

Simply Swords is designed with Better Combat in mind, and all baseline combat enhancing effects are left for Better Combat to handle. I don't plan to expand upon the vanilla combat system with Simply Swords, such as reach or sweeping attacks.
