### ISSUE TITLE
1.20.1 Forge 47.2.7

### ISSUE THREAD

**Issue by Krimatoria** [Sweenus/SimplySwords#155]
I don't have this mod. But for some reason there is this error)

> [06Mar2024 15:58:00.723] [Worker-ResourceReload-1/ERROR] [net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener/]: Couldn't parse data file simplyswords:runic_grimoire/ru_ru/entries/rune_etching/entry_rp_freeze from simplyswords:patchouli_books/runic_grimoire/ru_ru/entries/rune_etching/entry_rp_freeze.json
> com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 17 column 2 path $.pages[1].text
> 	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:526) ~[client-1.20.1-20230612.114412-srg.jar%23730!/:?]
> 	at net.minecraft.util.GsonHelper.m_263475_(GsonHelper.java:531) ~[client-1.20.1-20230612.114412-srg.jar%23730!/:?]
> 	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:581) ~[client-1.20.1-20230612.114412-srg.jar%23730!/:?]
> 	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_278771_(SimpleJsonResourceReloadListener.java:41) ~[client-1.20.1-20230612.114412-srg.jar%23730!/:?]
> 	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:29) ~[client-1.20.1-20230612.114412-srg.jar%23730!/:?]
> 	at net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener.m_5944_(SimpleJsonResourceReloadListener.java:17) ~[client-1.20.1-20230612.114412-srg.jar%23730!/:?]
> 	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.20.1-20230612.114412-srg.jar%23730!/:?]
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
> Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 17 column 2 path $.pages[1].text
> 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1042) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$28.readTerminal(TypeAdapters.java:747) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:791) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725) ~[gson-2.10.jar%2372!/:?]
> 	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1007) ~[gson-2.10.jar%2372!/:?]
> 	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:524) ~[client-1.20.1-20230612.114412-srg.jar%23730!/:?]
> 	... 13 more
>

**Comment by Sweenus** [comment]
You're using a very outdated version of Simply Swords. Please update to the latest version and see if you still have the issue.
