### ISSUE TITLE
weapon in config but not an item in game

### ISSUE THREAD

**Issue by owleague** [Sweenus/SimplySwords#157]
theres apparently a sword named dreadtide inside the config with its own ability and stats but theres no such obtainable item with the name or anything just curious as to if its a weapon that is unfinished or if its an addon weapon from another mod
![image_2024-03-07_201702040](https://github.com/Sweenus/SimplySwords/assets/55939948/5dc3771c-7471-49f5-9566-d85ae1fa5460)
![image_2024-03-07_201714299](https://github.com/Sweenus/SimplySwords/assets/55939948/6be752b5-fb98-4b3a-b2ea-0183af640c10)

**Comment by Sweenus** [comment]
Hi there,
This is future compat content. It technically already exists in the mod, it just won't register the item until the dependent mod updates to a specific version 🙂
