### ISSUE TITLE
Ender Dragon not dropping loots

### ISSUE THREAD

**Issue by YixiongZhou** [Sweenus/SimplySwords#163]
I change the config for both wither and ender dragon, wither did drop loot 100% but dragon are not dropping loot
  "minecraft:entities/wither": 1.0,
  "minecraft:entities/ender_dragon": 1.0,

**Comment by Sweenus** [comment]
You probably have loot tables that are overiding the loot inject. You would need to find whatever datapack / mod is adding hte loot tables and remove them. This is the only way to resolve the issue unfortunately.
