### ISSUE TITLE
Cant craft any of the weapons in the mod

### ISSUE THREAD

**Issue by CaptCO0I** [Sweenus/SimplySwords#164]
I know and have seen the crafting recipes for the weapons in the mod but when I try to craft them I cant. Are the all weapons uncraftable?

**Comment by Sweenus** [comment]
Unique weapons are uncraftable. Ordinary iron > netherite weapons are craftable.
Please provide some screenshot examples of the issue, and also a screenshot of the Simply Swords tab in the creative inventory.
