### ISSUE TITLE
中文翻译失效

### ISSUE THREAD

**Issue by wosw** [Sweenus/SimplySwords#171]
FABRIC v1.47.0-1.19.2版本上的中文翻译（zh_cn.json)文件在第521行少了一个（,）符号，导致中文版翻译失效
<img width="731" alt="屏幕截图_20240607_211458" src="https://github.com/Sweenus/SimplySwords/assets/68804143/18c4a518-0f01-4214-9392-df44f37fc33f">

**Comment by avirtual777** [comment]
该issue已经修复。
Already fixed in later versions. @Sweenus
