### ISSUE TITLE
Simply swords fabric breaking my game

### ISSUE THREAD

**Issue by elilmao** [Sweenus/SimplySwords#172]
Whenever i add the mod, when i launch it, the game opens but all textures are gone and when i boot up a world it straight up crashes.
![image](https://github.com/Sweenus/SimplySwords/assets/101594173/1a56ea69-d456-4a6e-a139-7067a13d50a1)
![image](https://github.com/Sweenus/SimplySwords/assets/101594173/f0d7335c-8609-45b2-b030-c2aebb82eeb2)

**Comment by Sweenus** [comment]
I believe this can happen if you don't allocate enough memory to Minecraft. This isn't Simply Swords specific
