### ISSUE TITLE
Game crashes when I put a unique weapon into my inventory?

### ISSUE THREAD

**Issue by ROTARY-PH0NE** [Sweenus/SimplySwords#174]
Haven't tried it with any other weapons, but it hard crashes when I try to get the Sunfire from the creative menu. Crash report is attached below, this is the error I get.
I've tried to update the mods, but instead of crashing when I try to get a weapon, it just crashes when I even try and load the game up, without an error code.

![image_2024-06-11_203205380](https://github.com/Sweenus/SimplySwords/assets/172459671/88cd4d68-cfe4-4bd4-909a-cb4fb2319bdb)

---- Minecraft Crash Report ----
// My bad.

Time: 2024-06-11 20:29:25
Description: Ticking player

java.lang.NoClassDefFoundError: net/spell_power/api/SpellSchools
	at net.sweenus.simplyswords.fabric.FabricHelperMethods.useSpellAttributeScaling(FabricHelperMethods.java:20)
	at net.sweenus.simplyswords.fabric.SimplySwordsExpectPlatformImpl.getSpellPowerDamage(SimplySwordsExpectPlatformImpl.java:19)
	at net.sweenus.simplyswords.SimplySwordsExpectPlatform.getSpellPowerDamage(SimplySwordsExpectPlatform.java)
	at net.sweenus.simplyswords.util.HelperMethods.commonSpellAttributeScaling(HelperMethods.java:508)
	at net.sweenus.simplyswords.item.custom.SunfireSwordItem.method_7888(SunfireSwordItem.java:80)
	at net.minecraft.class_1799.method_7917(class_1799.java:490)
	at net.minecraft.class_1661.method_7381(class_1661.java:256)
	at net.minecraft.class_1657.method_6007(class_1657.java:568)
	at net.minecraft.class_1309.method_5773(class_1309.java:2419)
	at net.minecraft.class_1657.method_5773(class_1657.java:283)
	at net.minecraft.class_3222.method_14226(class_3222.java:510)
	at net.minecraft.class_3244.method_18784(class_3244.java:269)
	at net.minecraft.class_2535.method_10754(class_2535.java:259)
	at net.minecraft.class_3242.method_14357(class_3242.java:172)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: net.spell_power.api.SpellSchools
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 20 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.sweenus.simplyswords.fabric.FabricHelperMethods.useSpellAttributeScaling(FabricHelperMethods.java:20)
	at net.sweenus.simplyswords.fabric.SimplySwordsExpectPlatformImpl.getSpellPowerDamage(SimplySwordsExpectPlatformImpl.java:19)
	at net.sweenus.simplyswords.SimplySwordsExpectPlatform.getSpellPowerDamage(SimplySwordsExpectPlatform.java)
	at net.sweenus.simplyswords.util.HelperMethods.commonSpellAttributeScaling(HelperMethods.java:508)
	at net.sweenus.simplyswords.item.custom.SunfireSwordItem.method_7888(SunfireSwordItem.java:80)
	at net.minecraft.class_1799.method_7917(class_1799.java:490)
	at net.minecraft.class_1661.method_7381(class_1661.java:256)
	at net.minecraft.class_1657.method_6007(class_1657.java:568)
	at net.minecraft.class_1309.method_5773(class_1309.java:2419)
	at net.minecraft.class_1657.method_5773(class_1657.java:283)

-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 6225
	Entity Name: rdthaler
	Entity's Exact location: -9.50, 76.00, -6.50
	Entity's Block location: World: (-10,76,-7), Section: (at 6,12,9 in -1,4,-1; chunk contains blocks -16,-64,-16 to -1,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_3222.method_14226(class_3222.java:510)
	at net.minecraft.class_3244.method_18784(class_3244.java:269)
	at net.minecraft.class_2535.method_10754(class_2535.java:259)
	at net.minecraft.class_3242.method_14357(class_3242.java:172)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 346028392 bytes (329 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1660
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2184
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3623
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 39882.91
	Virtual memory used (MB): 25989.66
	Swap memory total (MB): 23552.00
	Swap memory used (MB): 1075.30
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		archers: Archers (RPG Series) 1.0.7+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
		architectury: Architectury 9.1.12
		athena: Athena 3.1.2
		azurelibarmor: AzureLib Armor 2.0.3
		balm-fabric: Balm 7.2.1
		basicweapons: Basic Weapons 1.2.0
		bettercombat: Better Combat 1.8.3+1.20.1
		bookshelf: Bookshelf 20.1.8
		cave_dweller: Cave Dweller 1.4.0
		chipped: Chipped 3.0.6
		clay: Clay Soldiers 0.5.0
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		enchdesc: EnchantmentDescriptions 17.0.13
		fabric-api: Fabric API 0.91.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.3+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.7+29de845d77
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.3+c81d263177
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		farmersdelight: Farmer's Delight 1.20.1-1.4.3
		geckolib: GeckoLib 4 4.4.4
			com_eliotlash_mclib_mclib: mclib 20
		iris: Iris 1.6.17
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.2.0.27
		jewelry: Jewelry (RPG Series) 1.2.2+1.20.1
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 5.0.0+1.20
		luckyblocks: Lucky Blocks 1.4
		memoryleakfix: Memory Leak Fix 1.1.5
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.2.2
		mr_vanilla_refresh: Vanilla Refresh 1.4.19a
		naturalist: Naturalist 4.0.3
		origins: Origins 1.10.0
			apoli: Apoli 2.9.0
				additionalentityattributes: Additional Entity Attributes 1.3.0+1.20.0
				calio: Calio 1.11.0
				cardinal-components-base: Cardinal Components API (base) 5.2.1
				cardinal-components-entity: Cardinal Components API (entities) 5.2.1
				playerabilitylib: Pal 1.8.0
			reach-entity-attributes: Reach Entity Attributes 2.4.0
		origins-classes: Origins: Classes 1.7.0
		origins-plus-plus: Origins++ 2.2
		paladins: Paladins & Priests (RPG Series) 1.0.5+1.20.1
		pehkui: Pehkui 3.7.12+1.14.4-1.20.4
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		player-animator: Player Animator 1.0.2-rc1+1.20
		potionblender: Potion-Blender 1.1.0
		projectile_damage: Projectile Damage Attribute 3.2.2+1.20.1
		resourcefullib: Resourceful Lib 2.1.25
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		roughlyenoughitems: Roughly Enough Items 12.1.725
			error_notifier: Error Notifier 1.0.9
		runes: Runes 0.9.11+1.20.1
		simplyswords: Simply Swords 1.55.0-1.20.1
		skinlayers3d: 3d-Skin-Layers 1.6.2
		sodium: Sodium 0.5.8+mc1.20.1
		spell_engine: Spell Engine 0.12.5+1.20.1
		spell_power: Spell Power Attribute 0.9.19+1.20.1
		structure_pool_api: Structure Pool API 1.0+1.20.1
		trinkets: Trinkets 3.7.1
		waystones: Waystones 14.1.3
		wizards: Wizards (RPG Series) 1.0.5+1.20.1
		worldedit: WorldEdit 7.2.15+6463-5ca4dff
	Loaded Shaderpack: ComplementaryUnbound_r5.0.1.zip
		Profile: ULTRA (+0 options changed by user)
	Server Running: true
	Player Count: 1 / 8; [class_3222['rdthaler'/6225, l='ServerLevel[New World]', x=-9.50, y=76.00, z=-6.50]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.15.7-1.20.1

**Comment by Sweenus** [comment]
Hi, please ensure spell power attributes and simply swords are on the latest versions

**Comment by ROTARY-PH0NE** [comment]
![image](https://github.com/Sweenus/SimplySwords/assets/172459671/98d792b0-beb2-49bd-a0cc-e5c9599f4823)
This happened when I tried to boot it with the most recent ver. of spell power attributes.

**Comment by Sweenus** [comment]
You also need to update everything that depends on spell power attributes. Spell Engine, Paladins & Priests, Wizards, Archers, etc

**Comment by ROTARY-PH0NE** [comment]
Thank you for the quick replies and help. It works fine now.
