### ISSUE TITLE
FPS Lag

### ISSUE THREAD

**Issue by lukasgamer877** [Sweenus/SimplySwords#187]
When I have a weapon like this in my inventory, it drops at least 80 fps and I don't know why. I have already disabled all the animations and nothing. The game normally works for me at 120/140 fps and when I open the inventory in the weapons section of the mod it drops to 20/40 fps, also when I have them in the inventory this happens

**Comment by Sweenus** [comment]
Do you have the Model Gap Fix mod installed?

**Comment by lukasgamer877** [comment]
Yes, I had that mod. I uninstalled it and now the game runs fine. Thank you very much <3
