### ISSUE TITLE
Contained Remnant Bug

### ISSUE THREAD

**Issue by Mysandwich** [Sweenus/SimplySwords#188]
When the game goes to check if the contained remnant transforms it stops after finding the first one and so if you have multiple contained remnants only one is actually being checked every 5 mins. (this is on the latest forge release V1.55.0 for 1.20.1)

EDIT: Also a config for adjusting the percentage and time between checks would be nice.

**Comment by Sweenus** [comment]
This is not a bug, this is just the way it has been programmed.
I have gone ahead and increased the per 5min chance from 5% to 20% in the next release of the mod.
