### ISSUE TITLE
Sunfire crashes game

### ISSUE THREAD

**Issue by RubenTheRed** [Sweenus/SimplySwords#189]
Added Sunfire to inventory and got CTD 
MC launcher gives Error Code -1 with error messege "The game crashed whilst ticking entity
Error: java.lang.NoClassDefFoundError: net/spell_power/api/attributes/CustomEntityAttribute"

Trying to rejoin server gives error messege "Connection lost Internal Server Error"

**Comment by Sweenus** [comment]
You need to make sure you're using hte latest versions of Spell Power Attributes and Simply Swords
