### ISSUE TITLE
Magi

### ISSUE THREAD

**Issue by DarkestArchmage** [Sweenus/SimplySwords#190]
I've made many of containers and sat in the end with the rune in my inventory for a few hours but I've never gotten any of the magi stuff.

**Comment by Mysandwich** [comment]
Currently a bug in which the mod stops checking after it finds one in your inventory so having multiple is useless ( #188 )

**Comment by DarkestArchmage** [comment]
So the magi weapons are currently impossible to obtain?

**Comment by Mysandwich** [comment]
No not impossible just very time consuming as you can essentially only work on getting one at a time. [Craft x1 contained remnant > wait in end for it to turn into tampered remnant > hope for the magi relic (if you get enigma or dormant relic you have to get another contained remnant and repeat) > once you have the decaying relic you have to do one of three things for it to turn into the magi weapon you're wanting > repeat process for other two

**Comment by DarkestArchmage** [comment]
How do I transform it into one of the weapons?

**Comment by Mysandwich** [comment]
Magiblade: Has a chance to transform from decaying relic while walking _on_ skulk sensors.
Magispear: Has a chance to transform from decaying relic while under the effects of the vanilla darkness effect.
Magiscythe: Will transform from decaying relic if hit by Warden shriek.
As you can see they are all deep dark/skulk related.
