### ISSUE TITLE
I can't get Engima

### ISSUE THREAD

**Issue by katacanXD** [Sweenus/SimplySwords#191]
I killed about 1000 dragons, but I still couldn't get the Enigma. How can it be obtained in survival?

**Comment by Mysandwich** [comment]
Enigmas has a chance of being obtained from a tampered remnant. which you have a chance of obtaining when being in the end dimension while having both a contained remnant and runic tablet in your inventory. There's also currently a bug which only makes it to where it checks one in your inventory so having multiple is useless ( #188 )
