### ISSUE TITLE
Netherite Smithing Table Crafting recepies dont make sense

### ISSUE THREAD

**Issue by Lodel01** [Sweenus/SimplySwords#193]
I made a Mod pack for myself and put the Simply Swords mod with more than 100 more in it. I can't craft any of the netherite weapons, because I need the same netherite weapon to get the netherite weapon, which ofc doesn't make any sense. The same problem is with the Samurai Dynasty mod. It has some similar crafting recipes, which also have the same problem. The recipe doesn't interfere with the other, it just isint possible.
![Screenshot 2024-08-13 071940](https://github.com/user-attachments/assets/20606cbc-0ad4-42b2-948b-f263a51a3386)
![Screenshot 2024-08-13 071925](https://github.com/user-attachments/assets/adece8fb-6370-4d6c-9d9a-4bfcda02e533)

**Comment by Lodel01** [comment]
I have a solution for that. As it seems like, you can't look up how to craft a netherite weapon. You can just look what you can do with a diamond weapon. For example: You want the netherite katana. You can't look up how to craft it with the Keybind "R". You need to look what you can craft with a Diamond Katana with the Keybind "U". 
![image](https://github.com/user-attachments/assets/5518e22f-5046-4d87-8988-14e16cde1650)

**Comment by Sweenus** [comment]
I am not able to reproduce this issue with REI. I suspect you have another mod causing an issue.
Please isolation test with only Simply Swords, its dependencies, and REI (Or any equivelant) and see if the issue persists. If it does, let me know and I'll reopen the issue.
