### ISSUE TITLE
[Bug] Fatal Flicker effect name not added to en_us.json

### ISSUE THREAD

**Issue by Cicopath** [Sweenus/SimplySwords#194]
Fabric 1.20.1
Simply Swords 1.55.0

Title.
![image](https://github.com/user-attachments/assets/b00029e2-e360-474f-bacd-01de9cbcfb8c)

https://github.com/Sweenus/SimplySwords/blob/Architectury-1.20/common/src/main/resources/assets/simplyswords/lang/en_us.json#L529

**Comment by Sweenus** [comment]
Thank you for the report! This will be fixed in the next release
