### ISSUE TITLE
Damage values.

### ISSUE THREAD

**Issue by yungerdungusGithub** [Sweenus/SimplySwords#195]
Either i cant find the file within the config folder to change the damage types properly or they just dont work. Im going into 'weapon_attributes.json5' and changing the values of the rare uncraftable weapons to 40, (i know its huge its for balancing)  but i load up the server again, and looking through REI, the damage stays the same.

**Comment by Sweenus** [comment]
Thse values need to also be changed in the client config in order for the tooltips to display correctly
