### ISSUE TITLE
swords are too common in dungeon chests | 1.19 fabric V.1.04

### ISSUE THREAD

**Issue by Surpos0** [Sweenus/SimplySwords#2]
like i was having chest that was contaning 6 swords, and that is too mutch, but in my opinion this weapons are too powerful to be common. I don't want to start game with ultimate dimond godslaying fireslasher sword, that will kill all enemys on 1-2 hits, like men this is survival. 
And this is not joke this swords are like in every chest.
I like this mod, cuz of this models and compatibility with better combat, that make fights look so cool.
Or mayby add some config to change rarity of swords in chests.

**Comment by Sweenus** [comment]
Hey there, thanks for the report. I agree the default drop-rate is not quite where it needs to be, but it's something I find difficult to test so this feedback is useful.

There is a config for this though, I've split the loot pools into three categories that can be tweaked to adjust the rates. If possible can you adjust this and let me know what rates feel best to you?

I may end up further tweaking the loot tables to blacklist some chests. Finding a unique sword in a starter chest isn't exactly ideal.

**Comment by Sweenus** [comment]
Loot drop rates have been adjusted in the latest release - just make sure you delete your old config files so that the mod can generate new ones with the rate adjustments. I'll leave this ticket open a little while longer incase you have any feedback regarding the changes, then I'll close.

**Comment by Surpos0** [comment]
In my opinion its now much better then before but still i decreased spawn rate of loot cuz they are craftable so why not. And i think thats just my playstyle so there is why i decresed so much standard swords spawn rate.
This is my config:
  "unique_loot_table_weight": 0.0002,
  "standard_loot_table_weight": 0.002,
  "rare_loot_table_weight": 0.002,

**Comment by Sweenus** [comment]
Thanks for getting back to me with this. Sounds like the drops are at an acceptable level for now. I may decrease them closer to your configuration later down the line, depending on feedback.
