### ISSUE TITLE
Config for Gobber attributes

### ISSUE THREAD

**Issue by ImWhiff** [Sweenus/SimplySwords#20]
Would it be possible to add in the configs to have the option to configure weapon attributes from the Gobber mod? I customized the configs from the original mod, and I was hoping I could have similar attributes of that in the Gobber weapons from this mod.

**Comment by 48004800** [comment]
How to modify gobber weapon attributes

**Comment by ImWhiff** [comment]
Yeah, you can't change the attributes through the config file. I downloaded the source zip file and changed the attributes from within, and then built the jar file.

Here are the steps I did that worked for me.

1) Download the latest zip from the source by using the Architectury branch (Good news! Sweenus just had a major update [1.40])
![download zip](https://user-images.githubusercontent.com/122458396/216692398-ae223d21-2bfc-4c7f-b1c0-0ec856f5d741.png)

2) Unzip the file, and within, select the common folder
![common](https://user-images.githubusercontent.com/122458396/216693005-6182f58b-70a9-4ed7-a587-13ce20cc5d7a.png)

3) In the folder, go through the folders src->main->java->net->sweenus->simplyswords->item, and open the ModToolMaterial JAVA file
![modtoolmaterial](https://user-images.githubusercontent.com/122458396/216693716-81564f07-a29f-4cbf-941d-729508a04519.png)

4) Scroll down until you see the GOBBER attributes, and change them to your liking (note: the order goes from mining level, durability, mining speed, attack damage, and enchantability as written on the bottom)
![gobber](https://user-images.githubusercontent.com/122458396/216694032-33265c2a-c73b-4997-a3f1-e6b2345a2ca7.png)

5) After, go back to the first page of the main file and highlight as shown by just clicking 
![highlight](https://user-images.githubusercontent.com/122458396/216694190-baa65762-a542-4272-a0e2-43dc6b69ae2c.png)

6) Then, type cmd
![cmd](https://user-images.githubusercontent.com/122458396/216694256-03a63d3f-0c91-4c1b-a59a-066b6d1fb078.png)

7) The command prompt will show up, and simply type "gradlew build"
![gradlew build](https://user-images.githubusercontent.com/122458396/216694585-21829748-5a57-4d6e-a2c4-45a17a346fd7.png)

8) It should start building the jar file, and after some time, it will say BUILD SUCCESSFUL as shown
![5m](https://user-images.githubusercontent.com/122458396/216694847-1de4595e-30bb-437b-b277-687733c377a6.png)

9) Close the prompt and on the first page of the main folder, select forge or fabric depending on which you use
![fabric](https://user-images.githubusercontent.com/122458396/216695048-b748f8f1-f70c-45cf-838a-ac11519c1ac4.png)

10) Lastly, go through the files build->libs and the jar you want is the first one without the words
![simplyswords](https://user-images.githubusercontent.com/122458396/216695528-ddc7b96d-7b8c-4bad-82db-78fb65aadf4f.png)

I believe you can do this kind of internal changes with any mod that has open source file that does not have a private lib and has gradlew.bat in their zip, but anyone correct me if I am wrong. For example, the original Gobber mod has a private lib; therefore, you cannot gradlew build it and get the jar file with the changes you made.
![sweenus](https://user-images.githubusercontent.com/122458396/216699142-7867bf5c-2446-4b7d-bb1d-712781f2d701.png)
![gobber](https://user-images.githubusercontent.com/122458396/216698542-92fad3f0-6f9a-4e45-b2cd-976e4601da02.png)
As you can see, kwpugh has a private lib, and does not have the gradlew.bat property. I know this, because for some reason, changing the weapon attributes within the gobber config file causes axe and sword to have the same damage which makes no sense. But he said he will "have a look" to make it separate when he returns to modding in May.
![priv](https://user-images.githubusercontent.com/122458396/216698758-44a7d5ad-3d54-4eb5-a5d5-6bc21615470e.png)
Anyway, I hope this helps.

**Comment by Sweenus** [comment]
That's awesome that you figured that out, ImWhiff - and I'm sorry you had to go through that whole process!
I've gone ahead and added Gobber & Mythic Metal damage modifiers into the Weapon Attributes config in the latest version - hopefully that makes life a bit easier 🙂

**Comment by ImWhiff** [comment]
No worries lol. I really appreciate the update tho. Thanks once again!
