### ISSUE TITLE
Longsword Attack Range (Gobber Mod)

### ISSUE THREAD

**Issue by ImWhiff** [Sweenus/SimplySwords#21]
Longswords from the Gobber mod has an attack range of 2.5 while all the other longswords have a range of 2.9. I am not sure if it is because I configured these attributes (I changed durability, minespeed, attackdamage, and enchantability),

//GOBBER
    GOBBER(5, 1796, 8.5F, 5.5F, 13, () -> Ingredient.ofItems(Items.DIAMOND)),
    GOBBER_NETHER(6, 2562, 11.0F, 5.5F, 16, () -> Ingredient.ofItems(Items.DIAMOND)),
    GOBBER_END(7, 3916, 12.5F, 6.0F, 24, () -> Ingredient.ofItems(Items.DIAMOND));, 

but the thing is all the other Gobber weapons have same attack range as the other weapons'.  It's just the longswords that has the same attack range as normal sword.

![Iron Longsword](https://user-images.githubusercontent.com/122458396/212780428-3d8dedc8-300a-4cb6-903c-1d3ec6b21d3c.png)
![Gobber Longsword](https://user-images.githubusercontent.com/122458396/212780427-a9b30606-e9eb-4784-b8ba-41259f6e9acb.png)
![Diamond Twinblade](https://user-images.githubusercontent.com/122458396/212780426-43e48893-823d-4192-8ac7-3774db619f53.png)
![End Twinblade](https://user-images.githubusercontent.com/122458396/212780425-7e9f1db6-7fed-42d9-8822-87a8d6f1539d.png)

**Comment by Sweenus** [comment]
Thanks for the report!
Looks like I missed the compat weapons when I adjusted the longsword range in the most recent update.
I'll have this fixed for the next release

**Comment by ImWhiff** [comment]
Awesome!
As always, thanks for the amazing mod.
