### ISSUE TITLE
Unmet mod

### ISSUE THREAD

**Issue by Jrockcreeper** [Sweenus/SimplySwords#23]
Error message below.
______________________________________________________________________________________________________________________________________________
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install architectury, version 5.12.42 or later.
Unmet dependency listing:
	 - Mod 'Simply Swords' (simplyswords) 1.37-1.19.2 requires version 5.12.42 or later of architectury, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
______________________________________________________________________________________________________________________________________________
So I asked the architechtury mod and the verson that I got didn't work nor the version it's asking for.
______________________________________________________________________________________________________________________________________________

![Desktop Screenshot 2023 01 22 - 16 13 59 04](https://user-images.githubusercontent.com/96849298/213943208-b5dfc142-88b7-45b1-8421-ddf381543d71.png)

**Comment by Sweenus** [comment]
Please make sure you're downloading the correct version of Architectury. You need the Fabric one in this instance

**Comment by Jrockcreeper** [comment]
I spent yesterday trying to figure that out and that's the reason. I need to pay more attention to what I download LOL. Thanks btw.
