### ISSUE TITLE
Storm's Edge multiplayer right click bug

### ISSUE THREAD

**Issue by JeffTC72** [Sweenus/SimplySwords#24]
When playing on a server with this mod me and my friend found a bug with the storm's edge's right click. The first player to join the server will be referred to as player 1 and the second person is player 2.

Player 2 has a Storm's Edge, using right click should give player 2 forward momentum with a speed boost and haste. Instead, the momentum and boosts are applied to player 1 and player 2 only gets haste. Also the the cooldown is not applied for player 2, meaning he can send player 1 dashing though the whole map.

**Comment by Sweenus** [comment]
Thank you for the detailed report!
That is super weird. Do you happen to know if the same occurs with the Thunderbrand ability?

**Comment by JeffTC72** [comment]
Thunderbrand works fine, i've only seen this with the storms edge out of the weapons i have used so far

**Comment by JeffTC72** [comment]
Extra thing I just found: it only seems to happen when both player are holding the storms edge, when it's only one player it works fine

**Comment by Sweenus** [comment]
Thank you for that information!
I've been able to replicate the issue on my end and will try to have a fix ready for the next release

**Comment by Sweenus** [comment]
Just an update on this:
I've had to rerwite a little bit of the weapon logic, but I have the issue resolved on my end and will push the changes in the next update. Thank you again for bringing this issue to my attention!

**Comment by JeffTC72** [comment]
That's great. Do you happen to have an estimate of when the change will be live so I can add this version to my modded multiplayer server? Not that i expect anyone to find them for some time, but just in case. Either way I appreciate your work and I'm to have been of help. Cheers

**Comment by Sweenus** [comment]
New version containing the fix has been released - closing ticket
