### ISSUE TITLE
Crashing with the new update (1.40)

### ISSUE THREAD

**Issue by ImWhiff** [Sweenus/SimplySwords#26]
The 1.40 version crashes the game whilst loading a new world on fabric.

I made sure it was just this mod that was causing it, because I tried loading new worlds without the mod, with the version 1.37 which both worked, but new one crashes.

[crash-2023-02-03_15.38.38-client.txt](https://github.com/Sweenus/SimplySwords/files/10582685/crash-2023-02-03_15.38.38-client.txt)

**Comment by ImWhiff** [comment]
Nevermind. Downgrading fabric api 0.73 to 0.72 solved the problem. I'll leave this open in case this version not working with fabric api 0.73 is a problem.

Thanks for the awesome update as well as fixing the Gobber longsword range!

**Comment by Sweenus** [comment]
Glad you're enjoying the update!

I can't seem to replicate any crashes with either 0.73 or 0.72 of fabric api paired with Simply Swords, and don't see anything Simply Swords related in that crashlog - It may be another mod or something else causing the issue

**Comment by ImWhiff** [comment]
Downloading fabric api 0.73.2 fixed the crashing for me. Maybe it had something to do with the 0.73.0 version, unless that was the one you used to try replicate it.
