### ISSUE TITLE
Feature Request: Add a config for sounds

### ISSUE THREAD

**Issue by VeggeieDude** [Sweenus/SimplySwords#28]
Heya! The sounds of hitting something with the weapons is really loud, even when lowering the volume by a good amount. Do you think you can add a config to change the volume of the weapons?

**Comment by Sweenus** [comment]
Are you using Better Combat? If so, you can find this option in the Better Combat config

**Comment by Sweenus** [comment]
On second read, I think you might be refering to the impact sounds from Simply Swords.
I don't currently have a volume control for these, but I'll see about adding one in the next update.

In the interim, you might want to disable the impact sounds in the Simply Swords config. Look for "enable_weapon_impact_sounds"

**Comment by VeggeieDude** [comment]
Yes that sound, sorry haha. Ok, ill give it a try, thanks!

**Comment by Sweenus** [comment]
A config option for impact sounds has been added in the latest version 🙂
