### ISSUE TITLE
Some weapons display incorrectly when held by left handed player.

### ISSUE THREAD

**Issue by Dazsekszon** [Sweenus/SimplySwords#29]
![2023-02-12_13 26 30](https://user-images.githubusercontent.com/101024384/218311055-2627c369-9e4b-4886-9996-aa44897b81b7.png)
![2023-02-12_13 26 36](https://user-images.githubusercontent.com/101024384/218311059-738025fe-ff0e-4646-bdea-8b714258914e.png)

**Comment by Sweenus** [comment]
Thanks for the report!

I had to google this one - I had no idea this was even a feature in Minecraft.
I'll see what can be done about it.

**Comment by Sweenus** [comment]
I've fixed this issue and will be pushing a hotfix later today.
