### ISSUE TITLE
[SUGGESTION] Compatibility🙂

### ISSUE THREAD

**Issue by Willem07** [Sweenus/SimplySwords#30]
**I don't know if anyone wrote about it, but what about compatibility with the Epic Fight mod?**

**Comment by Willem07** [comment]
_I know that it is possible to create a datapack, but there are no such beautiful sounds and flying mjolnir and other animated weapons as there are with the Better Combat mod_

**Comment by Sweenus** [comment]
Hi there,

Epic Fight compatibility isn't something I'm planning on adding on my end.
The mod is very heavily designed around Better Combat, and adding in true Epic Fight compatibility, if it's even possible, is not something I have the time or resources to action.
