### ISSUE TITLE
Netherite Weapons Burn in Lava

### ISSUE THREAD

**Issue by Biokoro** [Sweenus/SimplySwords#31]
Netherite weapons get destroyed in lava unlike vanilla netherite items.

I believe it'd also be fair to make runic weapns lava-proof, given that they're upgraded from netherite items.
Possibly even special weapons, since they're so rare.
However, rare vanilla items such at tridents and totems are also not lava proof so I'm not 100% sure lol.
Possibly have special weapons being lava-proof as a toggle in the config.

_Forge:_ _43.2.0_
_Minecraft_ Version: _1.19.2_

_I've attached my latest log file in case it's needed._
[latest.log](https://github.com/Sweenus/SimplySwords/files/10719678/latest.log)

**Comment by Sweenus** [comment]
Hey there,

Thanks for the feedback!
I agree that it makes sense for runic & unique items to be lavaproof (except perhaps for the Bramblethorn).
I will try to have this implemented for the next update 🙂

**Comment by Sweenus** [comment]
This is now implemented in the latest update.
