### ISSUE TITLE
[SUGGESTION] Disabling weapons, runic effects and additional config options 

### ISSUE THREAD

**Issue by Xano11** [Sweenus/SimplySwords#33]
I really love this mod and I'm planning on using it as a main mod on my server's modpack. But, I think for the sake of configurability, it would help if specific weapons could be entirely removed from loot tables. Essentially, you could add a boonlean for every single weapon and putting it false would keep the weapon in game but available only from commands or the creative menu. Grants the player/server owner the ability to disable weapons they do not want for balancing or other reasons. Same here for the runic effects.

**Comment by Sweenus** [comment]
Thanks for the feedback!

I think this makes sense to implement as part of a greater overhaul to the loot config for the mod.
I will be working on this in the coming weeks 🙂

**Comment by Xano11** [comment]
To add to my initial inquiry/suggestion, here are two other suggestions I am providing for balancing and configuration.

1. Weapons that grant Haste, such as the Twisted Blade, can allow players to "farm" entities (Such as dummies from Target dummy mods) to get to the maximum amount of Haste stacks, allowing them to mine blocks at insane speeds. A suggestion would be to not use Haste, and in return : Either use the minecraft attribute : minecraft:generic.attack_speed or use a custom effect that only modifies attack speed, not mining speed.

2. Add a way to modify the combo damage, as certain weapons (Like the Halberd), have the possibility to deal extra damage on the last attack of the combo. With weapons such as the Thunderbrand, the weapon can achieve up to 7 hearts of damage (30 hearts to unarmored) to a fully maxed out netherite armored player, which is quite alot in Vanilla-esque PvP.

Again, I might seem picky, but I love the mod's feel, look and playability. One of the best weapon mods out here, but a bit of configuratibility would help server owners. Thanks again!

**Comment by Sweenus** [comment]
Thanks for the feedback!
I'll try to address your points as best I can.

1. I've avoided messing with attributes. I may be forced to look at these in future, but in the interim I would point you to the effects config. The duration of haste applied by each effect can be reduced to your liking.
In the case of the Twisted Blade in particular -  I would think the time spent generating those haste stacks before mining blocks would render this mechanic abuse redundant, as the haste duration is already quite short by default.

2. Combo damage modifiers are handled by Better Combat, so it's not possible for me to provide this kind of configuration.
Thankfully, Better Combat allows you to create datapacks to replace these values very easily - their github has lots of information on this.
That being said, that damage does seem a bit overtuned. I may lower the default modifiers on some of the weapons.

**Comment by Sweenus** [comment]
An Item & Runic weapon blacklist has been added to the latest release 🙂
