### ISSUE TITLE
Wildfire effect causing players to crash

### ISSUE THREAD

**Issue by VeggeieDude** [Sweenus/SimplySwords#34]
Heya! A friend playing on my server crashed because of the Wildfire effect and couldn't rejoin until I disabled the effect on the config.

Fabric 1.19.2, mod version 1.40.0

I'll send logs soon!

**Comment by Sweenus** [comment]
Thanks for the report!

Looking at the code, I can see potential for a null pointer exception when attempting to get the attacking entity for that effect.
Will need those logs to be sure.

**Comment by Sweenus** [comment]
Can't seem to replicate this issue on my end. Will need those logs when you get a chance.

**Comment by VeggeieDude** [comment]
Here u go!

https://pastebin.com/dqDP6BZT

**Comment by VeggeieDude** [comment]
So her and another friend were fighting each other lol. The one that was crashing had a runic rapier weapon, while the had a runic ring weapon. The runic ring was the one with the Wildfire effect. After hitting each other a few times she crashed lol

**Comment by Sweenus** [comment]
Thanks for that info!
I'll be deploying a fix today for versions 1.19.2 & 1.19.3.

**Comment by Sweenus** [comment]
Now fixed in the latest version.

**Comment by Kruscle** [comment]
This bug exists in the latest release for 1.18.2, any plans to revisit to fix?
