### ISSUE TITLE
Weapons don't scale properly on backslots

### ISSUE THREAD

**Issue by AeroUniverse** [Sweenus/SimplySwords#38]
![2023-02-17_20 16 50](https://user-images.githubusercontent.com/95264548/219826752-8c487715-11e4-437c-b8a1-d40226e3ac81.png)
![2023-02-17_20 17 27](https://user-images.githubusercontent.com/95264548/219826755-1a9d9b25-fd5a-4e66-869b-1313eaece67f.png)
![2023-02-17_20 17 24](https://user-images.githubusercontent.com/95264548/219826756-0753f276-b7f0-4a84-911f-ea6ac2b4a582.png)

Here are some pictures that show what I'm talking about

**Comment by Sweenus** [comment]
Hey there,
What version of backslot are you using?

**Comment by Sweenus** [comment]
I suspect you're on an older version of Backslot.
Please update to the latest version and things will be scaled correctly, as seen below:
![2023-02-18 17_52_31-Window](https://user-images.githubusercontent.com/48658188/219846204-53dd010e-a94f-44de-bc7a-18d088cb54ed.png)

**Comment by AeroUniverse** [comment]
> 

I tried downloading the latest version for 1.18.2(what I'm playing on) and nothing changed, is there a later version for 1.18.2? The latest I could find is 1.6.2.

**Comment by Sweenus** [comment]
Oh, I see - I believe the mod author changed the way these weapons scale, but didn't backport the change to their 1.18 version.
I may find the time to fix this in Simply Swords, but I think it would be ideal if they had the scaling work consistently across all their release versions.
