### ISSUE TITLE
Where is the legendary weapon language path?

### ISSUE THREAD

**Issue by snowjungsungwoo** [Sweenus/SimplySwords#39]
All normal weapons have been translated, but I don't know where the legendary weapon description file is.

**Comment by Sweenus** [comment]
Hey there,

The legendary/unique weapon descriptions are from line 483 in the lang file:
https://github.com/Sweenus/SimplySwords/blob/Architectury/common/src/main/resources/assets/simplyswords/lang/en_us.json

**Comment by Sweenus** [comment]
Just want to double check, did you find everything you were looking for?
