### ISSUE TITLE
incorrect display of the model with the back slot mod

### ISSUE THREAD

**Issue by lomovoyPlayer** [Sweenus/SimplySwords#4]
when using the already mentioned mod, the weapon becomes gigantic
![2022-08-28_01 30 54](https://user-images.githubusercontent.com/102898719/187044191-eb58624b-06b8-4525-a45a-030007ae917e.png)
![2022-08-28_01 31 04](https://user-images.githubusercontent.com/102898719/187044193-e02435c9-ae9b-460d-917f-bf25b9bd793c.png)
just in the hands it is displayed normally
![2022-08-28_01 31 20](https://user-images.githubusercontent.com/102898719/187044197-70baa9e6-bb15-489a-8de5-1b2abb7a55d2.png)

**Comment by Sweenus** [comment]
Thanks for the report!
It looks like BackSlot uses the head renderer of a model. I'll see if I can get the models to play nice for the next release.

**Comment by Sweenus** [comment]
I've updated the models to work better with the backslot mod - this will be fixed in the next release.

**Comment by Sweenus** [comment]
Fixed in latest release
