### ISSUE TITLE
Player/Chunk corruption 

### ISSUE THREAD

**Issue by Kasax007** [Sweenus/SimplySwords#40]
If on the Frozen Scythe Mending gets added in an anvil it corrupts/crashes the game. If the items stay in there because of a mod and it's an auto anvil, every restart won't help and the chunk gets corrupted.

**Comment by Kasax007** [comment]
Fabric 1.19.2 1.42.1

**Comment by Sweenus** [comment]
There is no weapon in Simply Swords called Frozen Scythe?

**Comment by Sweenus** [comment]
I'm assuming you've gotten this mixed up with another mod, so I'm going to close the ticket.
If I'm wrong, please feel free to reply with further detail of the issue.
