### ISSUE TITLE
Config files use JSON5 extension but do not accept valid JSON5

### ISSUE THREAD

**Issue by gigawhip** [Sweenus/SimplySwords#41]
The config files use the `.json5` extension which corresponds to the [JSON5 format](https://json5.org/). One feature of this file format is object keys don't have to be quoted if they are valid identifiers. Example:

```json5
// JSON5 only
{ some_key: true }

// JSON, or JSON5
{ "some_key": true }
```

You can confirm this in [an online validator](https://jsonformatter.org/json5-validator).

If you use this syntax in your config files, the game crashes on startup. I believe you are [parsing these files](https://github.com/Sweenus/SimplySwords/blob/Architectury/common/src/main/java/net/sweenus/simplyswords/config/Config.java#L53) as though they are regular JSON. Shockingly this works even though comments are invalid in regular JSON!

If you want just JSON with comments, use the `.jsonc` file extension. If you want to keep the `.json5` file extension, I recommend finding a proper JSON5 parser for Java. Otherwise when a user edits your config files with a code editor, it may auto-format the files in the conventional JSON5 style, which your current parser does not handle - that's how I found this error!

Another option would be to use [`.toml`](https://toml.io/en/) files, which are the most common format for Minecraft mod configs. They support JSON-serializable values as well as comments, and have much wider support than `.json5` or `.jsonc`.

**Comment by Sweenus** [comment]
Thank you for your suggestion!
I've been sitting on this one for a while, but the latest release has now moved over to using Cloth Config.
