### ISSUE TITLE
Promethium weapons do not regain durability

### ISSUE THREAD

**Issue by Orskelo** [Sweenus/SimplySwords#43]
When Mythic Metals is installed, weapons made from Promethium do not regain durability. I tested on a fresh install with just Mythic Metals, Simply Swords, a mod to show numeric durability numbers, and all the dependencies. Vanilla tools made from Promethium regained a durability every few seconds, but after minutes the modded weapons did not. It's possible Carmot weapons don't function properly with the extra looting level as well, but that's a bit harder to objectively prove.

**Comment by Sweenus** [comment]
Thanks for this report!
I've reproduced this issue on my end and will do some digging.

**Comment by Sweenus** [comment]
This is now fixed in the latest version.
