### ISSUE TITLE
Incompatability with Corails Tombstone that causes Corrupted playerdata

### ISSUE THREAD

**Issue by n0valey** [Sweenus/SimplySwords#46]
I am not sure if this is caused by simply swords or better combat, but when hitting a boss with the Corails Tombstone enchantment "Plague Bringer" on a sword, it crashes the player side and corrupts their playerdata serverside. This has happened multiple times, and some trial and error (my friend who was experiencing the crashes), it seems that some of the invisible effects of either better combat or simply swords like simplyswords.effect.gravity in combination of the Corails Tombstone enchantment crashes the game and prevents the player from rejoining unless the playerdata is deleted.

If there are any files, that you need to help figure out this problem, please let me know so i can provide them! It also happened with another player using the iron katana with plague bringer on it, same results where I needed to wipe the playerdata. 

Thank you!

**Comment by Sweenus** [comment]
Thank you for the report.
These deprecated effects have been removed in the latest release for 1.19.2, this should resolve the issue.
