### ISSUE TITLE
Identification problem

### ISSUE THREAD

**Issue by TheBluePlague** [Sweenus/SimplySwords#47]
I use Simply swords on my server as a addon for variation. Imedietly players started asking how you identify runic weapons that has been crafted or just gained. Ive been trying to search around to find answers as well as testing different methods in game but cant seem to figure out how to identify the runic power. It does have a power when using it you just cant see which power it has if you dont know the powers and how they look before hand. I might have missed something but at the moment i cant seem to figure out what to do.

**Comment by Sweenus** [comment]
Please double check that you have the same version of Simply Swords installed on the server and the client. This issue can occur when there is a version mismatch

**Comment by Sweenus** [comment]
Please let me know if you are able to resolve this issue following the steps above.

**Comment by TheBluePlague** [comment]
Indeed it seems like we have had 2 different versions for the clients and the server. thank you for the fast response and sorry i didn't get back too you until now. I haven't been home to test it until now. Cheers!
