### ISSUE TITLE
[Suggestion] Better config system for 1.19.2

### ISSUE THREAD

**Issue by itsdinkd** [Sweenus/SimplySwords#48]
Many, many mods are able to release updates and add its changes into the current config that someone has. 

Having to delete, regenerate, and reconfigure config files is very time consuming, especially if you are a modpack creator like myself and have a lot of customization. 

Please create a new system, or use a already available config API that allows concatenating new additions/changes to the config file that already exists.

**Comment by itsdinkd** [comment]
@Sweenus

**Comment by Sweenus** [comment]
A transition to Cloth Config is on the table. It won't be for a few months as I'm currently enjoying a break from development.

**Comment by Sweenus** [comment]
Cloth Config is now in use for versions 1.20.1+
This won't be backported, but the older versions won't see new content updates that require config regeneration.
