### ISSUE TITLE
add compatibility with companion/friendly fire?

### ISSUE THREAD

**Issue by meltremb** [Sweenus/SimplySwords#5]
i have friendly fire and companion installed so as to not hit my pets, it doesn't seem to work with the weapons from the mods and i keep killing my pets. possible to add compatibility?

**Comment by Sweenus** [comment]
Hey there,

Is it just the special on-hit weapon effects that are doing damage to your pets, or are the weapon swings damaging them as well?
And are you using Better Combat in your modpack?

**Comment by Sweenus** [comment]
Closing this due to lack of info. Better Combat added a friendly check to weapon swings in an update - this might resolve this issue.
