### ISSUE TITLE
Can't craft any of the normal weapons, no recipes unlocking

### ISSUE THREAD

**Issue by Chicken-Man** [Sweenus/SimplySwords#51]
After getting an iron ingot, none of the weapon crafting recipes unlock, and I can't craft any of the weapons. I can spawn the weapons in creative mode so I know the mod's installed properly.

**Comment by Sweenus** [comment]
Recipes will not show in the recipe book.
Please use either Patchouli or REI to view the recipes.

**Comment by Chicken-Man** [comment]
Yep that was the issue, thanks
