### ISSUE TITLE
Simply Swords & Levelz

### ISSUE THREAD

**Issue by oceancubes1** [Sweenus/SimplySwords#52]
Hello! How can i fix it?
I dont use Mythic Metals(
![2023-03-24_13 50 07](https://user-images.githubusercontent.com/128804324/227506928-d4d7a13f-b95e-4fa7-a5f3-5f9a9de44d8c.png)

**Comment by Sweenus** [comment]
Hey there,

The current implementation of Simply Swords LevelZ support assumes you have Mythic Metals. It will still function correctly, but that particular display will not look correct.

If this is bothering you, I would suggest removing Simply Swords.

**Comment by oceancubes1** [comment]
Hey!
I've fixed that by removing  mythic json files and it now it works correctly.
