### ISSUE TITLE
bugged weapons with better combat mod

### ISSUE THREAD

**Issue by anreww2910** [Sweenus/SimplySwords#53]
So, all of my weapons are bugged except a iron claymore im using, they dont do the animation that pulls them out and charges their critical bar thingy, this is only bugged in multiplayer and not on singleplayer for some reason and its very annoying, even vanilla minecraft weapons such as axes are bugged and just dont work

**Comment by Sweenus** [comment]
"animation that pulls them out and charges their critical bar thingy" I have no idea what this is referring to. It sounds like you're having an issue with another mod. Simply Swords doesn't touch vanilla Minecraft weapon behavior.
