### ISSUE TITLE
Wildfire effect can brick worlds if applied to exploding creepers

### ISSUE THREAD

**Issue by Queued4** [Sweenus/SimplySwords#54]
Creepers cause lingering potion effects after they explode and have an effect applied to them, so weapons that apply effects (like the wildfire effect) will functionally permaban a player from servers when it tries to spawn the lingering effect cloud in with them. It saves the info in the player's NBT data when they get kicked, so it can only be fixed if an admin edits the NBT data to remove any applied effects.

An error log would include something like this:
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.player.Player.m####()" because "p36169" is null

**Comment by Sweenus** [comment]
What version of Simply Swords are you using? All null pointers relating to effects should be fixed in the latest.

**Comment by Sweenus** [comment]
This issue was fixed in the latest versions for 1.19+. 1.18 versions may still encounter the issue. I'd recommend either updating your Minecraft version or removing the mod for now.

Closing the ticket, but if you have anything to add, please feel free to do so.
