### ISSUE TITLE
Attempting to grab a weapon from JEI cheat mode causes index out of bounds crash

### ISSUE THREAD

**Issue by Skidouche** [Sweenus/SimplySwords#55]
[crash-2023-04-02_16.59.57-client.txt](https://github.com/Sweenus/SimplySwords/files/11133349/crash-2023-04-02_16.59.57-client.txt)

**Comment by Sweenus** [comment]
There is nothing Simply Swords related in that crashlog. I'd suggest reporting this to JEI.
