### ISSUE TITLE
1.19.4

### ISSUE THREAD

**Issue by mrcrashmer** [Sweenus/SimplySwords#57]
This mod works on 1.19.4 without any problems and I use it on the server. But not most of the effects of legendary weapons crash the game. Is an update expected?

**Comment by Sweenus** [comment]
I've not updated to 1.19.4 as of yet. I wouldn't recommend using the mod on this version until I update (It's a mistake on my part that it even lets you launch on the wrong version).

I've yet to decide whether I'll be supporting or skipping 1.19.4.

**Comment by mrcrashmer** [comment]
1.19.4 is the latest version for Wild Update (most likely). Most probably, mods will be focused on this before the release of 1.20. Since it was for her that optimization was carried out and all new mods are being released. It would be nice to get an update. Although I believe that there will be smart ones who will create a fork for him :)
