### ISSUE TITLE
[FABRIC 1.19.2] Runic Halberd missing Runic Tablet recipe

### ISSUE THREAD

**Issue by SeaswimmerTheFsh** [Sweenus/SimplySwords#59]
The Runic Halberd can't be rerolled after crafting, due to it seemingly not having a smithing table recipe.

### Steps to reproduce:

1. Obtain a Netherite Halberd and two Runic Tablets
2. Make the Netherite Halberd into a Runic Halberd at a Smithing Table
3. Oops! You got Trailblaze!
4. Try to reroll the Runic Halberd using your second Runic Tablet at a Smithing Table
5. Come to the crushing realization you've now spent a Netherite Ingot and a Runic Tablet on a weapon that actively harms you for using it (#60)

Alternatively, you can press "U" (or your view uses keybind in REI/JEI) on a Runic Halberd. Nothing comes up, implying that the item has no registered recipes.

_Using the [All of Fabric 6](https://www.curseforge.com/minecraft/modpacks/all-of-fabric-6) modpack._

### Edit:
[Trent](https://github.com/dandin87) from the AOF6 team helped me find the exact issue, while there is a ``runic_halberd.json`` file in your recipes folder, there is not a ``runic2_halberd.json`` file.

```
{
  "type": "minecraft:smithing",
  "base": {
    "item": "simplyswords:runic_halberd"
  },
  "addition": {
    "item": "simplyswords:runic_tablet"
  },
  "result": {
    "item": "simplyswords:runic_halberd"
  }
}
```

**Comment by Sweenus** [comment]
Thanks for the report. Runic Warglaives also had this issue.
Fixed in the latest version for 1.19.2
