### ISSUE TITLE
[FABRIC 1.19.2] Trailblaze's weapon description does not match its actual properties

### ISSUE THREAD

**Issue by SeaswimmerTheFsh** [Sweenus/SimplySwords#60]
~~Trailblaze doesn't provide Fire Resistance on activation, or at least not enough to nullify the fire damage you receive from it.~~
Trailblaze's weapon description states it provides fire resistance, however its entry in the Runic Grimore says it does not and in practice it does not.

### Steps to reproduce:

1. Get a Runic weapon with Trailblaze on it
2. Hit a mob until Trailblaze triggers
3. Take fire damage for a few seconds
4. Oops! Well, you should probably reroll it if its "obviously broken", oh wait, that's a [Runic Halberd](https://github.com/Sweenus/SimplySwords/issues/59)... rip

_Using the [All of Fabric 6](https://www.curseforge.com/minecraft/modpacks/all-of-fabric-6) modpack._

**Comment by Sweenus** [comment]
Thanks for the report.
Trailblaze's description now properly reflects the ability.
It is intentional that it causes self damage.
