### ISSUE TITLE
[1.19.2] Molten Edge's right click effect gets preserved for longer whenever the user eats a golden apple

### ISSUE THREAD

**Issue by S8NLucifer** [Sweenus/SimplySwords#61]
Whenever you use Molten Edge's right click you can preserve the 5-second effect infinitely by eating a golden apple. This is OP because you can use it when surrounded by a bunch of entities to obtain numerous rows of hearts and then eat a golden apple to preserve the HP it gives forever instead of 5 seconds as written in the description of the weapon. This is possible to do in survival since I tried it myself next to the cow and sheep farm I made. The only way to lose the HP you gain with the effect is to take damage, for example: if you gained an extra bar of HP with the effect, you'll need to take 2 hits of a Stone Sword (with no armor) to remove it.

To replicate:
1.- Get Molten Edge.
2.- Spawn a bunch of hostile, passive or neutral mobs (sheep, zombies, piglins, etc.)
3.- Use Molten Edge's right click effect.
4.- Eat a normal golden apple inmediately after.

![Minecraft_ 1 19 2 - Multiplayer (3rd-party Server) 4_20_2023 1_01_57 AM (2)](https://user-images.githubusercontent.com/131338468/233286707-7b1e4f64-9c95-4596-b6f4-4036d71a003d.png)

**Comment by Sweenus** [comment]
Thanks for the report!
This weapon ability has been reworked in the latest version and no longer applies absorption.
