### ISSUE TITLE
[Suggestion] fix Shadowsting (Forge 1.19.2)

### ISSUE THREAD

**Issue by lBleyl** [Sweenus/SimplySwords#62]
Hello, thank you very much for the mod first, I love using it, however I have this problem: every time I use the right mouse click skill, I teleport into walls and suffer from suffocation damage, a viable solution would be to make the skill directional, where your character is looking the mini teleport, or something that avoids the player to enter the blocks, also sometimes falls from bridges one block wide because of this skill, another possible solution would be to remove the teleport, and leave only the blindness and increase its duration a little, because the teleport sometimes ends up being a double-edged sword. in addition, when the sword is used together with a shield the skill is used unintentionally sometimes, an interesting idea would be to have an option to change the skill activation button on the controls

**Comment by Sweenus** [comment]
This has been slightly reworked in the latest version, and should no longer cause issues. Thank you for the feedback!
