### ISSUE TITLE
[1.19.2] Registry remapping failed: Recieved Unknown ID map for minecraft:mob_effect

### ISSUE THREAD

**Issue by NicoTheCinderace** [Sweenus/SimplySwords#63]
Hi, so my friend is trying to join my server with SimplySwords installed, and every time he attempts to join it, he gets this really strange error message.

[https://cdn.discordapp.com/attachments/1030876429111525406/1104829979172278404/image.png](url)

The message is in the screenshot.

**Comment by Sweenus** [comment]
These are the deprecated effects that were removed in the latest version of the mod.
This means that your friends is trying to connect with a newer version of hte mod than the server has installed.

He will need to downgrade, or the server will need to update.
