### ISSUE TITLE
Switching to the diamond scythe damages me

### ISSUE THREAD

**Issue by FearAK** [Sweenus/SimplySwords#64]
Whenever I switch to wield my scythe it damages me a few hearts, is this intended?

**Comment by Sweenus** [comment]
What Scythe specifically? This is probably not Simply Swords' doing.

My guess is that you have a mod that adds attributes to gear, such as TierdZ or Gearifiers.

**Comment by FearAK** [comment]
It was the diamond scythe, but I think the cause was either improvableskills or nameless trinkets because it stopped happening after I removed those 2 mods.

**Comment by Sweenus** [comment]
Oh, you had already provided the type of Scythe in the title. My mistake!

I think you're probably right. I'm not familiar with either of those mods, but the base weapons from Simply Swords are almost entirely vanilla swords in terms of code, so unlikely to be a cause.
