### ISSUE TITLE
Echo rune bugs

### ISSUE THREAD

**Issue by Silent04** [Sweenus/SimplySwords#65]
I noticed the following bugs with Echo.
1. Echo does not spawn graves from the You're In Grave Danger mod on kill
2. Echo seems to ignore invincibility frames

**Comment by Sweenus** [comment]
Echo is now compatible with 'You're In Grave Danger' and should no longer cause loss of items, as of 1.46.1.
Echo is intended to ignore invincibility frames. If there is something problematic about this that I'm not considering, please do let me know.

Thanks again for your reports!
