### ISSUE TITLE
Forge Crash ticking lichblade

### ISSUE THREAD

**Issue by MrKashew** [Sweenus/SimplySwords#67]
[crash-2023-05-09_22.35.24-server.txt](https://github.com/Sweenus/SimplySwords/files/11438429/crash-2023-05-09_22.35.24-server.txt)
[crash-2023-05-09_22.31.09-server.txt](https://github.com/Sweenus/SimplySwords/files/11438430/crash-2023-05-09_22.31.09-server.txt)

**Comment by Sweenus** [comment]
Simply Swords is not 1.19.4 compatible. Please downgrade your Minecraft version or uninstall Simply Swords.
