### ISSUE TITLE
[SUGGESTION] Removing crafting recipes option in config

### ISSUE THREAD

**Issue by KevzCz** [Sweenus/SimplySwords#69]
I love the weapons but i would love to be able to remove certain weapon recipes (like removing the longswords recipe for example, would mean that you cant craft any type of longswords any more) to balance things out. Much appreciated!

**Comment by Sweenus** [comment]
Hey there,

I think you might be better off looking into an item removal mod, such as: https://legacy.curseforge.com/minecraft/mc-mods/item-obliterator

That would provide a more complete removal of an item, and can be employed across all installed mods.

**Comment by KevzCz** [comment]
Alright thanks!
