### ISSUE TITLE
[1.2.1+1.18.2] Boats cannot be retrieved

### ISSUE THREAD

**Issue by Cinex20** [Sweenus/SimplySwords#7]
Boats do not drop their items when destroyed. This happens even when using vanilla punches to break them.

**Comment by Sweenus** [comment]
Hey there,

This sounds like it might be an issue of another mod, as Simply Swords doesn't change any of this behaviour.
Can you please try with only Simply Swords installed and see if the issue still occurs?

**Comment by Sweenus** [comment]
No worries! Closing ticket
