### ISSUE TITLE
Nunchaku 

### ISSUE THREAD

**Issue by Boroso** [Sweenus/SimplySwords#70]

**Comment by Boroso** [comment]
pls add a Nunchuks weapon, its very cool and the last thing to complete the set of all these legendary weaponry

**Comment by Boroso** [comment]
and probably greatswords too, since claymores arent fat, and greatswords are so famous, its a shame they arent there

**Comment by Sweenus** [comment]
Hey there,

There are no good ways to animate whip/chain weapons, so these will not be added.
Greatswords don't add any gameplay value that isn't already fulfilled by a claymore, so they will not be added as a base weapon type. That being said, they may make appearances as Unique weapons, such as the pre-existing 'Lichblade', which is more Greatsword than it is Claymore.

**Comment by Boroso** [comment]
there are alot of cool weapon types u added and i've seen many unanimated weaponry still look cool, u cant add greatswords and nunchaku, thats just seems like a skill issue
