### ISSUE TITLE
No longer 3d models

### ISSUE THREAD

**Issue by Oliverbeagle** [Sweenus/SimplySwords#71]
After an update all of the swords reverted to pixel vanilla styles which i cant stand. I prefered the 3D style of the weapons but its no longer accessible.

**Comment by Sweenus** [comment]
3D models were replaced with 2D variants in the 1.40 update in February. A resourcepack was bundled with the mod that contains the legacy 3D models. Check your resourcepacks in-game.

**Comment by Oliverbeagle** [comment]
tnku
