### ISSUE TITLE
Server crash in 1.18.2 wildfire on phantoms

### ISSUE THREAD

**Issue by BrymalHS** [Sweenus/SimplySwords#73]
[crash-2023-05-20_13.34.00-server.txt](https://github.com/Sweenus/SimplySwords/files/11523170/crash-2023-05-20_13.34.00-server.txt)

Basically crashed the server when using a runic longsword with sweeping edge 3 and wildfire on some armoured zombies riding phantoms (phantoms were bigger than normal phantoms) that spawned from a spawner in a modded dungeon

**Comment by Sweenus** [comment]
This was a known bug with Wildfire, and has been fixed in recent versions.
The 1.18.2 versions of the mod do not have these fixes, so I'd recommend either updating Minecraft or avoiding the Wildfire runic effect.
