### ISSUE TITLE
Crash Upon adding mod and attempting to join server. 

### ISSUE THREAD

**Issue by ErisWhistles** [Sweenus/SimplySwords#75]
Hello,

I am a server hoster, I recently added the mod to the server, I have noticed that with new members joining this tick loop issue generates, this is isolated to this mod interacting with other mods or something in the code. 

[crash-2023-06-02_17.04.12-server.txt](https://github.com/Sweenus/SimplySwords/files/11638898/crash-2023-06-02_17.04.12-server.txt)

[latest (1).log](https://github.com/Sweenus/SimplySwords/files/11638867/latest.1.log)

**Comment by Sweenus** [comment]
Hi there,

I don't actually see anything specific to Simply Swords in your logs.
Your compatibility issue might lie elsewhere.
