### ISSUE TITLE
New tag to make entities immune to Weapon ability damage

### ISSUE THREAD

**Issue by BlackWarrior2004** [Sweenus/SimplySwords#79]
Like the title says. Currently weapon abilities(Eg: Mjolnir right click effect, Icewhisper\`s permafrost, etc) damage every thing(I haven\`t checked on players tho), even pets.
I installed this mod https://www.curseforge.com/minecraft/mc-mods/friendly-fire to see if it will prevent pet damage, but no they still get damaged.
Either having a tag, or a config option to make it so that only hostile entities take ability damage will be amazing

Thanks for this amazing mod 😀

**Comment by BlackWarrior2004** [comment]
Later found out they don`t damage/ target villagers

**Comment by Sweenus** [comment]
Sorry for the delay, and glad you're enjoying the mod!
Currently, the friendly fire logic takes into account PvP disabled players, villagers, and armor stands. I intend to add pets to this list in the next update.

If you think there are any other entities that should not be affected by damage, please let me know.

**Comment by Sweenus** [comment]
This update went live - pets are taken into consideration for friendly fire logic.
If you think anything else should be added to the entity blacklist, please do let me know.
