### ISSUE TITLE
Crash With CTM

### ISSUE THREAD

**Issue by Esseit** [Sweenus/SimplySwords#80]
Im having a crash on startup with this mod on forge 1.19.2 while using the Connected Textures Mod on forge version 42.2.14. I will provide the crash report below:

[Crash Report](https://pastebin.com/YGbT0iad)

To note, this occurs when using either CTM or Connectedness, removing either mod fixes the startup crash

**Comment by Sweenus** [comment]
Nothing in this log references Simply Swords. I think your compatibility issue is elsewhere.
