### ISSUE TITLE
There is an error in the Sinicization file

### ISSUE THREAD

**Issue by MeiyuanaQ** [Sweenus/SimplySwords#81]
The missing "," in line 521 of zh_cn.json makes the Sinicized file unusable
![image](https://github.com/Sweenus/SimplySwords/assets/55645051/0a51e0e3-c5bd-46bf-a2a5-5f1481ea6b78)

**Comment by Sweenus** [comment]
Thanks for the report! This is now fixed as of version 1.48.0
