### ISSUE TITLE
[Mythic Metals Compat] Durasteel and Copper sections are incomplete

### ISSUE THREAD

**Issue by TrueDevron** [Sweenus/SimplySwords#83]
The Durasteel and Copper compact for Mythic Metals only have 1 weapon for each section, that being the Durasteel Greathammer and Copper Longsword, any other weapons that should be created are not present. Is there something that went wrong during loading?

MC version: 1.21 (Quilt)
SS version: 1.48.0 
MM version: 1.18.1-hotfix

**Comment by Sweenus** [comment]
These weapons tiers were mostly skipped to encourage the base swords in Mythic Metals, and to save development time.
I don't intend to add the remaining weapons for these teirs, but I am open to pull requests from any contributors.
