### ISSUE TITLE
[Suggestion] Upgraded Netherite & Ultimerite support (Forge)

### ISSUE THREAD

**Issue by ShinryuAspect** [Sweenus/SimplySwords#84]
Hi, first things first, I really love the mod and I came upon this mod when checking Better Combat. I was amazed to find it has built in support for such an enhancing mod.
I'd like to see if it would be possible to add an addon to support the [Upgraded Netherite](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite) & [Ultimerite](https://www.curseforge.com/minecraft/mc-mods/upgraded-netherite-ultimerite) set of mods, as I find those the go to for an expanded Vanilla+ experience without the need on introducing new metals to the game.
Anyhow, keep up the good work on such a good mod and thank you in advanced.

**Comment by Sweenus** [comment]
Hi there,
Thank you for the kind words, and I'm glad you're enjoying the mod!

No additional compat is currently being worked on.
Please see the mod Knaves' Needs for additional Simply Swords compat, here: https://www.curseforge.com/minecraft/mc-mods/knaves-needs
If you have any suggestions for mod compatibility, I'd recommend reaching out to the Knave's Needs dev 🙂
