### ISSUE TITLE
Crossbow offhand

### ISSUE THREAD

**Issue by loyyord** [Sweenus/SimplySwords#86]
Holding a crossbow in the offhand will stop the weapons from rendering in animations

I cant get a picture showing it but you can see the animation ending without a sword being rendered
![image](https://github.com/Sweenus/SimplySwords/assets/56915440/b4f49c50-0d99-4fbc-9f4a-5f0a437978a0)

**Comment by Sweenus** [comment]
Hi there,

I'm not able to reproduce any kind of issue like this.
This also sounds like an issue with Better Combat, not Simply Swords.
