### ISSUE TITLE
guidebook patch for Patchouli MC 1.20.1

### ISSUE THREAD

**Issue by xyxt1c** [Sweenus/SimplySwords#87]
In Patchouli for MC 1.20.1 (fabric), the tooltip of the guidebook says 'Invalid Book: simplyswords:runic_grimoire'.

[https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120/](https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120/)

**Comment by Sweenus** [comment]
This should be fixed in the latest version.
