### ISSUE TITLE
[1.20.1] Simply Swords crashes on entering server with Patchouli

### ISSUE THREAD

**Issue by samjviana** [Sweenus/SimplySwords#88]
Minecraft: 1.20.1
Forge Version: 47.1.0
Simply Swords: 1.48.0-1.21
Patchouli: 1.20.1-80-FORGE

Simply Swords works well alone, and works just fine with Patchouli in a SMP world, but when using them in a server, the server starts normally, but the player (client) crashes while entering in the server. 
Sadly I couldn't get any log files that describes this error in details, the only thing I have is this screenshot:

<details>
<summary> Image </summary>

![minecraft_error](https://github.com/Sweenus/SimplySwords/assets/30292497/d63ceaac-c461-4b6f-b799-e1561c175ade)

</details>

**Comment by Sweenus** [comment]
This should be fixed in the latest version.
