### ISSUE TITLE
[SUGGESTION] Compat for more mods

### ISSUE THREAD

**Issue by Sunconure11** [Sweenus/SimplySwords#9]
Hellish materials, adabranium, more gems, better nether, better end, and winterly would all be good places to start

**Comment by Sunconure11** [comment]
Diamold and additional additions are some more

**Comment by Sweenus** [comment]
Thanks for the suggestion!
Additional mod support will be on the backburner for a while, as it's incredibly time intensive to implement and sustain - but I'm open to taking a look at it further down the line once some more baseline features have been implemented.
