### ISSUE TITLE
Advanced Netherite mod compat?

### ISSUE THREAD

**Issue by SamuelUlep** [Sweenus/SimplySwords#90]
I saw this [issue](https://github.com/Sweenus/SimplySwords/issues/37) regarding `Forgero` compat and `Better Netherite` compat, it also mentioned `Advanced Netherite` but was not brought up in the conversation. Is there a compat with `Advanced Netherite` in the works?

**Comment by Sweenus** [comment]
Hi there,

No additional compat is currently being worked on.
Please see the mod Knaves' Needs for additional Simply Swords compat, here: https://www.curseforge.com/minecraft/mc-mods/knaves-needs
If you have any suggestions for mod compatibility, I'd recommend reaching out to the Knave's Needs dev 🙂
