### ISSUE TITLE
Performance issues with ''Mythic Metals'' Metallurgium animated weapons.

### ISSUE THREAD

**Issue by SkiTTbicepS** [Sweenus/SimplySwords#91]
Hi! 

I recently noticed some perf issues.
Please check the screenshots. I am sorry, but I cannot provide more information since I am not a programmer or coder. :) 
Anyways, the mod is great! We are enjoying it!
Thank you very much! 
![2023-07-24_02 12 40](https://github.com/Sweenus/SimplySwords/assets/140356649/5548b1c2-7241-4b84-9153-a0d644d9cdd1)
![2023-07-24_02 12 49](https://github.com/Sweenus/SimplySwords/assets/140356649/09bd0398-3f21-4319-9dd9-729469190cf9)

**Comment by Sweenus** [comment]
Hey there,

Glad you're enjoying the mod!
I'd hazard a guess that you have Model Gap Fix installed, please see: https://github.com/MehVahdJukaar/modelfix-multi/issues/27

Let me know if removing it resolves your issue

**Comment by SkiTTbicepS** [comment]
Hey Sweenus! 

Thanks for the quick reply!
You were right! Hoooly FPS increase.
Thanks a lot!
![2023-07-24_15 01 00](https://github.com/Sweenus/SimplySwords/assets/140356649/828aca36-1a2c-4c4c-b860-d37de308f24a)

**Comment by Sweenus** [comment]
Woohoo! Glad that fixed the issue 🙂
Enjoy your frames!
