### ISSUE TITLE
Mythic Metals Upgrade path changed

### ISSUE THREAD

**Issue by Sinogard** [Sweenus/SimplySwords#93]
hi I've noticed that the Metallurium and celestium alloy weapons dont use the new unobtanium smithing template to upgrade netherite gear into those variants. I've tried adding them in a datapack but haven't had success with it. If you could update them to use that for consistency i would be very appreciative.

**Comment by Sweenus** [comment]
Thanks for bringing this to my attention!
This has been implemented in the latest 1.20.1 release.
