### ISSUE TITLE
Icewhisper damaging pets and not granting exp on passive kill

### ISSUE THREAD

**Issue by yeboiTeki** [Sweenus/SimplySwords#94]
Hey there, I noticed that the Icewhisper will damage my pets, even with a friendly fire mod installed. 
Also it doesnt grand exp when using the AOE-Ability. 

Not sure if this is intended.

**Comment by Sweenus** [comment]
Hi there,

Pet checks have been added to the intenral friendly fire logic, and the damage types of ice weapons have been changed to a normal magic damage source (may or may not resolve the passive kill exp issue).
