### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Rogenar** [Sweenus/SimplySwords#97]
When I add the Simply Swords FABRIC v1.50.0-1.20.1 version, I get such an error and it is very unrelated, but the FABRIC v1.48.2-1.20.1 version does not have this error.
![sss1](https://github.com/Sweenus/SimplySwords/assets/122460325/1909bb3b-8dc3-4bf2-b6a0-9c1ac567cf43)
[latest.log](https://github.com/Sweenus/SimplySwords/files/12182691/latest.log)

**Comment by Sweenus** [comment]
It looks like the Enchantments Plus mod requires a specific version of Cloth Config instead of a version range.
This isn't a Simply Swords issue. You will need to report the issue to the Enchantments Plus dev.
